package agents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

// TransformContext holds all the context needed to generate modernpath_agents.md
type TransformContext struct {
	InitiativeID   int
	InitiativeName string
	SourceSystemID   int
	TargetSystemID   int
	SourceSystemName string
	TargetSystemName string
	ProjectType    string

	// Transform items (source files)
	SourceFiles []SourceFile

	// Source system documentation
	SourceDocs []SourceDoc

	// Target system documentation
	Docs []Document

	// Specifications
	Specs          []SpecFile
	SpecCategories []string

	// Metadata
	GeneratedAt string
	CLIVersion  string
}

// SourceFile represents a file to be transformed
type SourceFile struct {
	Name       string
	FilePath   string
	Language   string
	TotalLines int
	Purpose    string
	Summary    string
	Approach   string // rewrite, refactor, wrap
	Priority   string // high, medium, low
}

// Document represents a system document
type Document struct {
	ID      string
	Title   string
	Tier    string
	Angle   string
	Summary string
}

// SourceDoc represents a source system document synced locally
type SourceDoc struct {
	ID       string
	Title    string
	Tier     string
	Angle    string
	Summary  string
	FilePath string // Relative path in .modernpath/source_docs/
}

// SpecFile represents a specification file
type SpecFile struct {
	Name     string
	Category string
	Path     string
}

const agentsMDTemplate = `# ModernPath Transformation Guide

> **Generated by ModernPath CLI** on {{ .GeneratedAt }}

This project is a **transformation initiative** to modernize legacy code.

## Context

- **Initiative**: {{ .InitiativeName }} (ID: {{ .InitiativeID }})
- **Source System**: {{ .SourceSystemName }} (ID: {{ .SourceSystemID }})
- **Target System**: {{ .TargetSystemName }} (ID: {{ .TargetSystemID }})
- **Transform Items**: {{ len .SourceFiles }} files selected for transformation

## Local Resources

All resources needed for transformation have been synced locally.

### Source Code (.modernpath/source/)

The following legacy files have been synced for transformation:

| File | Language | Lines | Purpose |
|------|----------|-------|---------|
{{- range .SourceFiles }}
| {{ .FilePath }} | {{ .Language }} | {{ .TotalLines }} | {{ if .Purpose }}{{ .Purpose }}{{ else }}-{{ end }} |
{{- end }}

**Usage**: Read these files directly from ` + "`" + `.modernpath/source/` + "`" + ` to understand the legacy implementation.

### Source System Documentation (.modernpath/source_docs/)

Documentation for the **source/legacy** system you're modernizing:

{{- if .SourceDocs }}
| Document | Tier | Angle | Summary |
|----------|------|-------|---------|
{{- range .SourceDocs }}
| [{{ .Title }}](.modernpath/source_docs/{{ .FilePath }}) | {{ .Tier }} | {{ if .Angle }}{{ .Angle }}{{ else }}-{{ end }} | {{ if .Summary }}{{ .Summary }}{{ else }}-{{ end }} |
{{- end }}
{{- else }}
No source documentation synced yet. Source docs are synced automatically with ` + "`" + `modernpath transform sync` + "`" + `.
{{- end }}

**Usage**: These docs explain how the legacy system works. Essential reading before transforming each file.

### Target System Documentation (.modernpath/<slug>/)

Documentation for the **target** system you're building:

{{- if .Docs }}
{{- range .Docs }}
- ` + "`" + `{{ .Title }}.md` + "`" + `
{{- end }}
{{- else }}
No target documentation synced yet. Run ` + "`" + `modernpath docs sync` + "`" + ` to download.
{{- end }}

### Specifications (.modernpath/specs/)

Transformation specifications organized by category:

{{- if .SpecCategories }}
{{- range .SpecCategories }}
- ` + "`" + `{{ . }}/` + "`" + ` - {{ . | title }} specifications
{{- end }}
{{- else }}
No specifications synced yet. Select an initiative with ` + "`" + `modernpath work select` + "`" + ` to sync specs.
{{- end }}

## CLI Tools for Additional Context

When you need information beyond the synced files, use these CLI commands:

### Read Source Files

` + "```" + `bash
# Read any file from the source codebase
modernpath read-file src/other/file.php

# Read specific line range
modernpath read-file src/auth/login.php --start=50 --end=100
` + "```" + `

### Read Documentation

` + "```" + `bash
# Search documentation by title
modernpath read-doc "Authentication"

# List all documentation
modernpath read-doc --list

# Get docs by tier
modernpath read-doc --tier=module

# Get docs by tier and angle
modernpath read-doc --tier=subsystem --angle=architecture
` + "```" + `

### Search and Ask

` + "```" + `bash
# Full-text search across docs and code
modernpath search "how does authentication work"

# Ask questions about the codebase
modernpath ask "What is the data flow for user login?"
` + "```" + `

## Transformation Workflow

1. **Read the specs** in ` + "`" + `.modernpath/specs/` + "`" + ` to understand requirements
2. **Review source docs** in ` + "`" + `.modernpath/source_docs/` + "`" + ` to understand the legacy system
3. **Review source files** in ` + "`" + `.modernpath/source/` + "`" + ` for each item
4. **Check target docs** under ` + "`" + `.modernpath/<system-slug>/` + "`" + ` (e.g. ` + "`" + `architecture/` + "`" + `) for target patterns
5. **Use CLI** for additional source file context when needed
6. **Write modernized code** in the target project folder
7. **Follow the approach** specified for each file (rewrite/refactor/wrap)

## File-by-File Transformation

{{- range .SourceFiles }}

### {{ .Name }}
{{ if .FilePath }}
- **Source Path**: ` + "`" + `.modernpath/source/{{ .FilePath }}` + "`" + `
{{- end }}
- **Language**: {{ .Language }}
- **Lines**: {{ .TotalLines }}
{{- if .Purpose }}
- **Purpose**: {{ .Purpose }}
{{- end }}
{{- if .Summary }}
- **Summary**: {{ .Summary }}
{{- end }}
{{- if .Approach }}
- **Approach**: {{ .Approach }}
{{- end }}
{{- if .Priority }}
- **Priority**: {{ .Priority }}
{{- end }}

{{- end }}

## Questions?

Use the ask command for AI-powered answers:

` + "```" + `bash
modernpath ask "How should I handle the database connection in the new system?"
` + "```" + `

---

*This file was generated by ModernPath CLI v{{ .CLIVersion }}. Regenerate with ` + "`" + `modernpath transform sync` + "`" + `.*
`

// Generate creates the modernpath_agents.md file
func Generate(ctx *TransformContext, outputPath string) error {
	funcMap := template.FuncMap{
		"title": strings.Title,
	}

	tmpl, err := template.New("agents_md").Funcs(funcMap).Parse(agentsMDTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	if ctx.GeneratedAt == "" {
		ctx.GeneratedAt = time.Now().Format("2006-01-02 15:04:05")
	}
	if ctx.CLIVersion == "" {
		ctx.CLIVersion = "dev"
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ctx); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	// Ensure output directory exists
	if dir := filepath.Dir(outputPath); dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create output directory: %w", err)
		}
	}

	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}

// GenerateFromManifest generates modernpath_agents.md from the manifest file
func GenerateFromManifest(manifestPath, outputPath string) error {
	// Read manifest
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return fmt.Errorf("failed to read manifest: %w", err)
	}

	var manifest struct {
		InitiativeID         int    `json:"initiative_id"`
		InitiativeName       string `json:"initiative_name"`
		SourceSystemID int    `json:"source_system_id"`
		TargetSystemID int    `json:"target_system_id"`
		TotalFiles           int    `json:"total_files"`
		SyncedFiles          int    `json:"synced_files"`
		SyncedAt             string `json:"synced_at"`
		Files                []struct {
			Name       string `json:"name"`
			FilePath   string `json:"file_path"`
			Language   string `json:"language"`
			TotalLines int    `json:"total_lines"`
			Purpose    string `json:"purpose"`
			Summary    string `json:"summary"`
		} `json:"files"`
	}

	if err := json.Unmarshal(data, &manifest); err != nil {
		return fmt.Errorf("failed to parse manifest: %w", err)
	}

	// Build context
	ctx := &TransformContext{
		InitiativeID:   manifest.InitiativeID,
		InitiativeName: manifest.InitiativeName,
		SourceSystemID:   manifest.SourceSystemID,
		TargetSystemID:   manifest.TargetSystemID,
		SourceSystemName: fmt.Sprintf("System %d", manifest.SourceSystemID),
		TargetSystemName: fmt.Sprintf("System %d", manifest.TargetSystemID),
		SourceFiles:    make([]SourceFile, 0, len(manifest.Files)),
	}

	for _, f := range manifest.Files {
		ctx.SourceFiles = append(ctx.SourceFiles, SourceFile{
			Name:       f.Name,
			FilePath:   f.FilePath,
			Language:   f.Language,
			TotalLines: f.TotalLines,
			Purpose:    f.Purpose,
			Summary:    f.Summary,
		})
	}

	// Scan for specs
	specsDir := filepath.Join(filepath.Dir(manifestPath), "..", "specs")
	if entries, err := os.ReadDir(specsDir); err == nil {
		for _, entry := range entries {
			if entry.IsDir() {
				ctx.SpecCategories = append(ctx.SpecCategories, entry.Name())
			}
		}
	}

	// Scan for docs
	docsDir := filepath.Join(filepath.Dir(manifestPath), "..", "docs")
	if entries, err := os.ReadDir(docsDir); err == nil {
		for _, entry := range entries {
			if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".md") {
				name := strings.TrimSuffix(entry.Name(), ".md")
				ctx.Docs = append(ctx.Docs, Document{
					Title: name,
					Tier:  "synced",
					Angle: "local",
				})
			}
		}
	}

	return Generate(ctx, outputPath)
}
