package cmd

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// cliReferenceTarget is where `modernpath install` writes the reference this
// binary renders from its own command tree. It is generated from the build
// that wrote it, so it cannot drift from the binary the way a hand-written
// manual does, and `install --check` reports a stale copy as drift — a merged
// CLI change that was not followed by a reinstall shows up at the next check
// instead of in a session that trusted the old text (tooling self-sufficiency plan, C4;
// USER:2026-09-12, D-3). The managed AGENTS block and the mp-process-cli skill
// point at it; nothing loads it into a session unless a lookup needs it.
const cliReferenceTarget = ".modernpath/cli-reference.md"

// renderCLIReference renders one deterministic markdown document for the
// whole visible command tree: every command's path, summary, long help,
// usage, and flags with type, default and description. No timestamps, no
// build stamp, so the same tree always renders the same bytes.
func renderCLIReference(root *cobra.Command) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# `%s` command reference\n\n", root.Name())
	b.WriteString("<!-- TOOL-OWNED. Generated by `modernpath install` from this build's command tree; `install --check` reports an edited or stale copy as drift. -->\n\n")
	b.WriteString("Every verb, flag, default and prerequisite the installed `modernpath` binary\n")
	b.WriteString("carries, rendered from the binary itself. Per-verb `--help` prints the same\n")
	b.WriteString("text. The store-backed sequences that combine these verbs are the\n")
	b.WriteString("`mp-process-cli` skill; the process they serve is `.modernpath/rdd/PROCESS.md`.\n\n")

	if root.Long != "" {
		b.WriteString(strings.TrimSpace(root.Long))
		b.WriteString("\n\n")
	}
	if flags := flagRows(root.PersistentFlags()); len(flags) > 0 {
		b.WriteString("## Global flags\n\n")
		writeFlagTable(&b, flags)
		b.WriteString("\n")
	}

	b.WriteString("## Commands\n\n")
	for _, c := range visibleCommands(root) {
		fmt.Fprintf(&b, "- [`%s`](#%s) — %s\n", c.CommandPath(), anchorFor(c), c.Short)
	}
	b.WriteString("\n")

	for _, c := range visibleCommands(root) {
		fmt.Fprintf(&b, "## `%s`\n\n", c.CommandPath())
		if c.Short != "" {
			b.WriteString(c.Short)
			b.WriteString("\n\n")
		}
		if c.Long != "" {
			b.WriteString(strings.TrimSpace(c.Long))
			b.WriteString("\n\n")
		}
		fmt.Fprintf(&b, "```\n%s\n```\n\n", c.UseLine())
		if flags := flagRows(c.LocalNonPersistentFlags()); len(flags) > 0 {
			writeFlagTable(&b, flags)
			b.WriteString("\n")
		}
		if shared := flagRows(localPersistentFlags(c)); len(shared) > 0 {
			b.WriteString("Flags this command shares with its subcommands:\n\n")
			writeFlagTable(&b, shared)
			b.WriteString("\n")
		}
		for _, a := range inheritedFlagTables(c) {
			fmt.Fprintf(&b, "Inherited from `%s`:\n\n", a.path)
			writeFlagTable(&b, a.rows)
			b.WriteString("\n")
		}
	}
	return b.String()
}

// visibleCommands walks the tree depth-first in the order cobra prints it,
// skipping hidden commands, the auto-generated help command, and groups whose
// only handler is the unknown-argument guard (they still appear, since their
// help is what a reader lands on; only cobra's own additions are dropped).
func visibleCommands(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		subs := append([]*cobra.Command(nil), c.Commands()...)
		sort.SliceStable(subs, func(i, j int) bool { return subs[i].Name() < subs[j].Name() })
		for _, s := range subs {
			if s.Hidden || s.Name() == "help" || s.Name() == "completion" {
				continue
			}
			out = append(out, s)
			walk(s)
		}
	}
	walk(root)
	return out
}

type flagRow struct{ name, typ, def, usage string }

func flagRows(fs *pflag.FlagSet) []flagRow {
	var rows []flagRow
	fs.VisitAll(func(f *pflag.Flag) {
		// cobra adds -h only to the command being executed, so it would
		// appear under whichever command rendered the reference and nowhere
		// else — a nondeterminism, not information.
		if f.Hidden || f.Name == "help" {
			return
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		def := f.DefValue
		if f.Value.Type() == "bool" && def == "false" || def == "[]" {
			def = ""
		}
		rows = append(rows, flagRow{name: name, typ: f.Value.Type(), def: def, usage: f.Usage})
	})
	return rows
}

// inheritedFlags is one ancestor's persistent flags as the reference prints
// them under a subcommand.
type inheritedFlags struct {
	path string
	rows []flagRow
}

// inheritedFlagTables returns the persistent flags a subcommand inherits,
// grouped by the ancestor that declares them, nearest first. Without this a
// group's persistent flag was printed only on the group — `--piece` is
// declared on `process` and on `working-set`, so `working-set pull --piece`
// was a documented flag that appeared in no verb's table (BACKLOG-TOOL-68).
// The root's own persistent flags are deliberately not repeated here: they
// apply to every verb and the reference lists them once under "Global flags",
// so echoing them under all ~90 sections would be noise, not information.
func inheritedFlagTables(c *cobra.Command) []inheritedFlags {
	var out []inheritedFlags
	seen := map[string]bool{}
	for a := c.Parent(); a != nil && a.HasParent(); a = a.Parent() {
		var rows []flagRow
		for _, r := range flagRows(localPersistentFlags(a)) {
			// localPersistentFlags already drops a name an ancestor only
			// redeclares, so a redeclared flag prints under the ancestor that
			// first declared it — the farther one — and this map should never
			// fire. It is kept so that a change there cannot make one command
			// list the same flag twice.
			if seen[r.name] {
				continue
			}
			seen[r.name] = true
			rows = append(rows, r)
		}
		if len(rows) > 0 {
			out = append(out, inheritedFlags{path: a.CommandPath(), rows: rows})
		}
	}
	return out
}

// localPersistentFlags returns the persistent flags this command declares
// itself, not the ones inherited from its ancestors. The root's are the ones
// the reference lists once at the top; a group's are listed again under each
// subcommand that inherits them (inheritedFlagTables).
func localPersistentFlags(c *cobra.Command) *pflag.FlagSet {
	out := pflag.NewFlagSet(c.Name(), pflag.ContinueOnError)
	c.PersistentFlags().VisitAll(func(f *pflag.Flag) {
		if c.InheritedFlags().Lookup(f.Name) == nil {
			out.AddFlag(f)
		}
	})
	return out
}

func writeFlagTable(b *strings.Builder, rows []flagRow) {
	b.WriteString("| Flag | Type | Default | Meaning |\n|---|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", r.name, r.typ, cell(r.def), cell(r.usage))
	}
}

// cell keeps a value inside one table cell: pipes are escaped and newlines
// become spaces, so a multi-line usage string cannot break the table.
func cell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.Join(strings.Fields(s), " ")
	return s
}

func anchorFor(c *cobra.Command) string {
	return strings.ReplaceAll(c.CommandPath(), " ", "-")
}
