package cmd

import (
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func flagNames(c *cobra.Command) []string {
	var names []string
	collect := func(f *pflag.Flag) {
		if !f.Hidden && f.Name != "help" {
			names = append(names, f.Name)
		}
	}
	c.LocalNonPersistentFlags().VisitAll(collect)
	localPersistentFlags(c).VisitAll(collect)
	return names
}

func findCommand(t *testing.T, root *cobra.Command, path []string) *cobra.Command {
	t.Helper()
	c, _, err := root.Find(path)
	if err != nil {
		t.Fatalf("command %v: %v", path, err)
	}
	return c
}

// The installed CLI reference is rendered from the binary's own command tree
// so it cannot drift from the build that wrote it (tooling self-sufficiency
// plan C4, USER:2026-09-12). These checks pin what makes it usable as a
// lookup: every visible verb is there with its flags, the loop verbs carry the
// prerequisites their long help was given (plan B1–B7), and the rendering is
// deterministic so `install --check` compares bytes, not luck.
// availableCommands walks the tree by cobra's own notion of availability,
// independently of the renderer's visibleCommands, so a command the renderer
// drops fails here instead of vanishing from both sides.
func availableCommands(c *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, s := range c.Commands() {
		if !s.IsAvailableCommand() {
			continue
		}
		out = append(out, s)
		out = append(out, availableCommands(s)...)
	}
	return out
}

func TestCLIReferenceRendersEveryVisibleCommandAndFlag(t *testing.T) {
	ref := renderCLIReference(rootCmd)
	available := availableCommands(rootCmd)
	if len(available) < 40 {
		t.Fatalf("only %d available commands walked — the walk is broken", len(available))
	}
	for _, c := range available {
		if !strings.Contains(ref, "## `"+c.CommandPath()+"`") {
			t.Errorf("reference has no section for %q", c.CommandPath())
		}
		for _, name := range flagNames(c) {
			if !strings.Contains(ref, "`--"+name+"`") && !strings.Contains(ref, ", --"+name+"`") {
				t.Errorf("reference never lists flag --%s of %q", name, c.CommandPath())
			}
		}
	}
	for _, want := range []string{
		"## `modernpath author trace`",
		"## `modernpath working-set select`",
		"## `modernpath factory evidence`",
		"## `modernpath process reconcile`",
		"## `modernpath process findings add`",
		"## Global flags",
		"`--api-url`",
	} {
		if !strings.Contains(ref, want) {
			t.Errorf("reference is missing %q", want)
		}
	}
	if strings.Contains(ref, "modernpath help") || strings.Contains(ref, "modernpath completion") {
		t.Error("reference lists cobra's own help or completion commands")
	}
	if strings.Contains(ref, "| `-h, --help`") {
		t.Error("reference lists cobra's -h flag, which appears only under the executing command")
	}
}

func TestCLIReferenceIsDeterministic(t *testing.T) {
	a := renderCLIReference(rootCmd)
	b := renderCLIReference(rootCmd)
	if a != b {
		t.Fatal("two renders of the same tree differ — install --check would report drift on every run")
	}
	for _, stamp := range []string{"Auto generated by", "20"} {
		if strings.Contains(a, "###### "+stamp) {
			t.Fatalf("reference carries a timestamp-like footer %q", stamp)
		}
	}
}

// Plan B1–B7: the per-verb prerequisites are authored once on the command and
// reach both --help and the reference. Each verb is checked for the fact a
// session most often got wrong.
func TestLoopVerbsCarryTheirPrerequisitesInHelp(t *testing.T) {
	cases := map[string][]string{
		"author gate":          {"--prerequisite", "cold-review", "packet aggregate", "members before the epic", "trace first"},
		"author trace":         {"full packet aggregate", "process next -v", "Fingerprint: line of working-set pull", "--for-review", "bare ids"},
		"author advance":       {"content-shadow hash", "working-set pull <gate-id>", "Members before the epic"},
		"working-set select":   {"--replaces", "--suspend", "--resume", "--put-down", "earlier reason stays", "--for-review"},
		"factory evidence":     {"RED", "never\nlower or upper", "evidence of its own", "delivered (merged) revision", "RED commit"},
		"process findings add": {"correctness, security, data_loss, contract,\ntraceability and testability", "never defaults to the most blocking pair", "--severity note"},
		"process reconcile":    {"never applies a human-gated transition", "nothing to do", "--piece", "cascade mode is report"},
		// REQ-CROSS-413 (BACKLOG-TOOL-22): the recovery verb states the
		// attestation semantics — it re-pins an applied entry gate to the current
		// aggregate on a USER: decision that attests the move was immaterial; a
		// material change needs re-review, not re-apply.
		"process reapply-entry": {"applied entry gate", "current packet aggregate", "--decision", "USER:", "immaterial", "re-review", "PENDING_VERIFICATION", "READY"},
		// REQ-CROSS-421 (EPIC-CLI-022): the sanctioned reopen names its basis
		// vocabulary, the USER: reason, the gate id and the apply step.
		"author demote": {"USER:", "--apply", "DEMOTE-", "reversed-decision", "defect", "superseded", "--superseded-by", "IN_REVIEW or DONE", "no prerequisite"},
	}
	// Tooling gaps filed 2026-09-12/13 (process/tooling-gaps.md): the facts a
	// session met as an unexplained refusal are now named where the verb is
	// looked up. Help text only — the behaviors themselves are loop work.
	surfaced := map[string][]string{
		// unlisted category → map[category:[is invalid]]; ~260-char --body → empty 500
		"process findings add": {"feasibility, scope, other", "category: is invalid", "--body", "422 naming the field"},
		// completion gate omits the UR; a stuck governed gate has no dismiss path
		"author gate": {"user requirement (UR-", "lists only SRs", "omits members not yet DONE", "IN_REVIEW or DONE —\n               not yet",
			"Retiring a stuck gate", "--supersedes <old>", "opened once", "gate-withdraw"},
		// evidence on the epic or the SRs does not cover the UR
		"factory evidence": {"user requirement", "does not cover the UR", "--pass the UR"},
		// 260-character verification method → empty server 500
		"author requirement": {"255", "422 naming the field", "author update --detail"},
		"author epic":        {"255", "--description is free text"},
		"author update":      {"255", "422 naming the field", "--verification-method", "--detail"},
		// REQ-CROSS-384 (EPIC-CLI-018): a record patch moves the scope context;
		// the push re-stamps the sections the server reports stale and says so
		"working-set push": {"scope context", "re-stamped N section(s)", "--restamp", "reports as stale"},
		// several held pieces print as no selection; the aggregate is independent of the process revision (REQ-CROSS-412)
		"process next": {"SEVERAL current pieces", "--piece <id>", "independent of the process revision", "process_revision"},
	}
	for path, wants := range surfaced {
		cases[path] = append(cases[path], wants...)
	}
	for path, wants := range cases {
		c := findCommand(t, rootCmd, strings.Fields(path))
		for _, want := range wants {
			if !strings.Contains(c.Long, want) {
				t.Errorf("%s --help never says %q", path, want)
			}
		}
	}
}

// REQ-CROSS-412: the packet aggregate no longer folds the server's compiled
// process revision, so `process next` help must no longer describe that fold.
// A presence loop cannot catch text that should be GONE, so the old markers are
// forbidden explicitly (builder note F-CROSS412-R2-02).
func TestProcessNextHelpNoLongerDescribesTheProcessRevisionFold(t *testing.T) {
	c := findCommand(t, rootCmd, []string{"process", "next"})
	for _, forbidden := range []string{
		"compiled process revision",
		"The planning scope\nchanged since the decision was pinned",
	} {
		if strings.Contains(c.Long, forbidden) {
			t.Errorf("process next --help still describes the process-revision fold: %q", forbidden)
		}
	}
}
