package cmd

import (
	"fmt"
	"os"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

var (
	// Version is set at build time
	Version = "dev"

	// Flags
	verbose bool
	apiURL  string
)

var rootCmd = &cobra.Command{
	Use:   "modernpath",
	Short: "ModernPath CLI - AI-powered codebase analysis and documentation",
	Long: `ModernPath CLI provides access to your codebase documentation
and analysis generated by the ModernPath platform.

Initialize a project with 'modernpath init', then use search and ask
to explore your documentation, and 'work' commands to manage epics and tasks.`,
	Version: Version,
	CompletionOptions: cobra.CompletionOptions{
		DisableDefaultCmd: true,
	},
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func init() {
	rootCmd.PersistentFlags().BoolVarP(&verbose, "verbose", "v", false, "verbose output")
	rootCmd.PersistentFlags().StringVar(&apiURL, "api-url", "", "ModernPath API URL (default: from config or beta.modernpath.ai)")

	// Add subcommands
	rootCmd.AddCommand(initCmd)
	rootCmd.AddCommand(statusCmd)
	rootCmd.AddCommand(searchCmd)
	rootCmd.AddCommand(authCmd)
	// Note: syncCmd removed - use 'docs sync' instead
	// Note: reviewCmd moved to work.go as 'work review'
	// Note: contextCmd removed - functionality merged into ask command with --format flag
}

// Helper functions for output
func printSuccess(format string, a ...interface{}) {
	color.Green("✓ "+format, a...)
}

func printError(format string, a ...interface{}) {
	color.Red("✗ "+format, a...)
}

func printInfo(format string, a ...interface{}) {
	color.Cyan("→ "+format, a...)
}

func printWarning(format string, a ...interface{}) {
	color.Yellow("⚠ "+format, a...)
}
