package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

var (
	// Version is set at build time
	Version = "dev"

	// Flags
	verbose bool
	apiURL  string
)

var rootCmd = &cobra.Command{
	Use:   "modernpath",
	Short: "ModernPath CLI - AI-powered codebase analysis and documentation",
	Long: `ModernPath CLI provides access to your codebase documentation
and analysis generated by the ModernPath platform.

Initialize a project with 'modernpath init', then use search and ask
to explore your documentation, and 'work' commands to manage epics and tasks.`,
	Version: Version,
	// Error paths return errors so exit codes are honest (REQ-CROSS-210);
	// without this every such error also dumps the full usage screen.
	SilenceUsage: true,
	CompletionOptions: cobra.CompletionOptions{
		DisableDefaultCmd: true,
	},
}

// applyGroupUnknownArgGuard closes the D5 shape tree-wide: a group command
// (subcommands, no Run/RunE) that receives a token which is not one of its
// subcommands must error, not print help and exit 0 — that silent success is
// how `modernpath dev <tool>` masqueraded as working (REQ-CROSS-210;
// pre-PR review finding A1). Bare group invocations still show help.
// groupGuardAnnotation marks a group whose handler is this guard rather than
// a hand-written one. The guard mutates a shared tree, so without a marker a
// second application (or a test running after one) cannot tell a guarded
// group from a group that always had a handler.
const groupGuardAnnotation = "modernpath.group-unknown-arg-guard"

func applyGroupUnknownArgGuard(c *cobra.Command) {
	if len(c.Commands()) > 0 && c.Run == nil && c.RunE == nil {
		if c.Annotations == nil {
			c.Annotations = map[string]string{}
		}
		c.Annotations[groupGuardAnnotation] = "1"
		c.RunE = func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			return fmt.Errorf("unknown command %q for %q — run '%s --help'", args[0], cmd.CommandPath(), cmd.CommandPath())
		}
	}
	for _, sub := range c.Commands() {
		applyGroupUnknownArgGuard(sub)
	}
}

func Execute() {
	applyGroupUnknownArgGuard(rootCmd)
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func init() {
	rootCmd.PersistentFlags().BoolVarP(&verbose, "verbose", "v", false, "verbose output")
	rootCmd.PersistentFlags().StringVar(&apiURL, "api-url", "", "ModernPath API URL (default: from config or api.modernpath.ai)")

	// Add subcommands
	rootCmd.AddCommand(initCmd)
	rootCmd.AddCommand(statusCmd)
	rootCmd.AddCommand(searchCmd)
	rootCmd.AddCommand(authCmd)
	// Note: syncCmd removed - use 'docs sync' instead
	// Note: reviewCmd moved to work.go as 'work review'
	// contextCmd lives in context.go — it backs the installed context hook
}

// Helper functions for output
func printSuccess(format string, a ...interface{}) {
	color.Green("✓ "+format, a...)
}

// Errors and warnings go to stderr so that --json and other pipeable output
// stays parseable on stdout (REQ-CROSS-210 D13, RUN:2026-08-18). The newline
// is conditional, mirroring fatih/color's own behavior — callers pass "\n"
// in their formats and must not get double-spaced (pre-PR review finding).
func printError(format string, a ...interface{}) {
	color.New(color.FgRed).Fprintf(color.Error, ensureTrailingNewline("✗ "+format), a...)
}

func ensureTrailingNewline(format string) string {
	if strings.HasSuffix(format, "\n") {
		return format
	}
	return format + "\n"
}

func printInfo(format string, a ...interface{}) {
	color.Cyan("→ "+format, a...)
}

func printWarning(format string, a ...interface{}) {
	color.New(color.FgYellow).Fprintf(color.Error, ensureTrailingNewline("⚠ "+format), a...)
}
