package rdd

// REQ-CROSS-013 / TASK-SY-404 — RED-first port of the retired node
// op-builder's suite, plus the hash-parity pins generated from that builder.
// The node side is gone, so these pins are the surviving record of the two
// implementations agreeing: they still hold the Go builder to those hashes.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/modernpath/cli/internal/manifest"
)

func detailWithCriteria() string {
	return strings.Join([]string{
		"- **Status:** READY",
		"- **Acceptance criteria:**",
		"  - GIVEN a thing WHEN poked THEN it reacts.",
		"  - GIVEN only given THEN result.",
		"  - plain statement criterion",
		"- **Tests:** —",
	}, "\n")
}

func TestParseCriteriaSplitsGWTAndStatements(t *testing.T) {
	criteria := ParseCriteria(detailWithCriteria(), "REQ-TST-001")
	if len(criteria) != 3 {
		t.Fatalf("want 3 criteria, got %d", len(criteria))
	}
	first := criteria[0].(map[string]any)
	if first["given"] != "a thing" || first["when"] != "poked" || first["then"] != "it reacts." {
		t.Fatalf("GWT parse wrong: %v", first)
	}
	if first["external_id"] != "REQ-TST-001#AC1" || first["position"] != 1 {
		t.Fatalf("criterion identity wrong: %v", first)
	}
	second := criteria[1].(map[string]any)
	if second["given"] != "only given" || second["then"] != "result." {
		t.Fatalf("GIVEN/THEN (no WHEN) parse wrong: %v", second)
	}
	if _, hasWhen := second["when"]; hasWhen {
		t.Fatalf("no-WHEN criterion must omit the when key: %v", second)
	}
	third := criteria[2].(map[string]any)
	if third["statement"] != "plain statement criterion" {
		t.Fatalf("statement parse wrong: %v", third)
	}
}

// Hash-parity pins — generated by running the node op-builder on the same
// inputs (2026-07-28), and kept after it was retired. If these fail the
// canonicalization drifted from JSON.stringify semantics and a re-sync would
// churn every content hash.
func TestRequirementOpHashParityWithNodeBuilder(t *testing.T) {
	op := BuildRequirementOp(Req{
		ID:     "REQ-TST-001",
		Title:  `Title with · dots & "quotes"`,
		Ctx:    "TST",
		Stage:  "MVP",
		Status: "READY",
		Source: "`docs/10` · USER:2026-07-22 · EPIC-TST-001 · INV-TST-001",
		Detail: detailWithCriteria(),
	})
	if op.Type != "upsert_requirement" {
		t.Fatalf("wrong type %q", op.Type)
	}
	p := op.Payload
	if p["work_status"] != "READY" || p["context"] != "TST" || p["stage"] != "MVP" {
		t.Fatalf("field mapping wrong: %v", p)
	}
	cites := p["source_citations"].([]any)
	if len(cites) != 4 {
		t.Fatalf("want 4 citations, got %d", len(cites))
	}
	c0 := cites[0].(map[string]any)
	if c0["kind"] != "doc" || c0["ref"] != "docs/10" {
		t.Fatalf("citation classify wrong: %v", c0)
	}
	if c1 := cites[1].(map[string]any); c1["kind"] != "user" {
		t.Fatalf("USER: citation wrong: %v", c1)
	}
	// pins regenerated from the node builder after REQ-CROSS-222 added the
	// full-fidelity capture fields (detail_md/source_raw here)
	const nodeHash = "b5302eb659495c0562bf6683575f291ec8e8b8a93950d28c76542587c964ea0f"
	if p["content_hash"] != nodeHash {
		t.Fatalf("hash parity broken:\n  go:   %v\n  node: %s", p["content_hash"], nodeHash)
	}
}

func TestEmptyStageHashesAsNullLikeNode(t *testing.T) {
	op := BuildRequirementOp(Req{ID: "REQ-TST-002", Title: "t", Ctx: "TST", Stage: "", Status: "DONE", Source: "—"})
	const nodeHash = "3255be9be181cf85f62f62a3188d34e5b9ab9e8d090f3c195096ea66c06b0c87"
	if op.Payload["content_hash"] != nodeHash {
		t.Fatalf("empty-stage hash parity broken: %v != %s", op.Payload["content_hash"], nodeHash)
	}
	if op.Payload["stage"] != nil {
		t.Fatalf("empty stage must serialize null, got %v", op.Payload["stage"])
	}
}

func TestContentHashKeyOrderIndependent(t *testing.T) {
	a := map[string]any{"x": 1, "y": []any{map[string]any{"b": "2", "a": "1"}}}
	b := map[string]any{"y": []any{map[string]any{"a": "1", "b": "2"}}, "x": 1}
	if ContentHash(a) != ContentHash(b) {
		t.Fatal("hash must be key-order independent")
	}
}

const epicRecord = `# EPIC-TST-001 — Test epic title

Intro.

## Requirements in this epic
` + "`REQ-TST-001` · `REQ-TST-002` · `REQ-TST-001`" + `

## Approval
_pending_
`

func TestEpicOpTitleAndLinksFromRecord(t *testing.T) {
	op := BuildEpicOp(Epic{ID: "EPIC-TST-001"}, epicRecord)
	p := op.Payload
	if p["title"] != "Test epic title" {
		t.Fatalf("title from H1 wrong: %v", p["title"])
	}
	ids := p["requirement_external_ids"].([]any)
	if len(ids) != 2 || ids[0] != "REQ-TST-001" || ids[1] != "REQ-TST-002" {
		t.Fatalf("requirement links wrong: %v", ids)
	}
	if _, has := p["approval"]; has {
		t.Fatal("_pending approval must not sync")
	}
}

func TestEpicOpRecordedApprovalSyncs(t *testing.T) {
	approved := strings.Replace(epicRecord, "_pending_",
		"**APPROVED** — USER:2026-07-22: ship it.", 1)
	op := BuildEpicOp(Epic{ID: "EPIC-TST-001"}, approved)
	approval, ok := op.Payload["approval"].(map[string]any)
	if !ok {
		t.Fatal("recorded approval must sync")
	}
	if approval["source_tag"] != "USER:2026-07-22" || approval["approved_at"] != "2026-07-22T00:00:00.000000Z" {
		t.Fatalf("approval fields wrong: %v", approval)
	}
}

func TestRQGateStates(t *testing.T) {
	answered := BuildRQGateOp(RQ{
		ID: "RQ-101", Title: "T", Heading: "RQ-101 (2026-07-20) T — ✅ APPROVED", Date: "2026-07-20",
		State: "closed", Line: 10, Body: "Resolved per USER:2026-07-20 decision.",
	})
	if answered.Payload["state"] != "answered" || answered.Payload["source_tag"] != "USER:2026-07-20" {
		t.Fatalf("closed RQ with USER tag must answer: %v", answered.Payload)
	}
	if answered.Payload["answerer"].(map[string]any)["kind"] != "human" {
		t.Fatal("answered gate needs a human answerer")
	}

	open := BuildRQGateOp(RQ{ID: "RQ-102", Title: "T2", Heading: "RQ-102 T2 — DECISION NEEDED", State: "decision-needed", Line: 20, Body: "?"})
	if open.Payload["state"] != "open" {
		t.Fatalf("decision-needed RQ must stay open: %v", open.Payload["state"])
	}

	dismissed := BuildRQGateOp(RQ{ID: "RQ-103", Title: "T3", Heading: "RQ-103 T3 ✅", State: "closed", Line: 30, Body: "closed without a source"})
	if dismissed.Payload["state"] != "dismissed" {
		t.Fatalf("closed-without-source must dismiss, never fake an answer: %v", dismissed.Payload["state"])
	}

	oq := BuildOQGateOp(OQ{ID: "OQ-A1", Title: "Where?", Full: "Where does the schema live?", Resolved: true, Line: 5})
	if oq.Payload["state"] != "answered" || oq.Payload["source_tag"] != "DOC:process/08-open-questions.md" {
		t.Fatalf("resolved OQ gets the DOC: tag: %v", oq.Payload)
	}
}

func TestApprovalGateOpenAndClosedForms(t *testing.T) {
	// Lower is set because REQ-CROSS-139 refuses to OPEN a gate over an epic with
	// no evidence. This test is about the open/answered forms, not that rule.
	openGate, ok := BuildApprovalGateOp(Epic{ID: "EPIC-TST-001", State: "awaiting-approval", Record: "epics/EPIC-TST-001.md", Lower: "**LOWER_VERIFIED**"}, epicRecord)
	if !ok {
		t.Fatal("awaiting-approval epic must gate")
	}
	if openGate.Payload["external_id"] != "APPROVE-EPIC-TST-001" || openGate.Payload["state"] != "open" {
		t.Fatalf("open approval gate wrong: %v", openGate.Payload)
	}
	holds := openGate.Payload["holds"].([]any)
	if len(holds) != 2 {
		t.Fatalf("holds must cover the epic's requirements: %v", holds)
	}

	approved := strings.Replace(epicRecord, "_pending_", "**APPROVED** — USER:2026-07-23: reviewed.", 1)
	closedGate, ok := BuildApprovalGateOp(Epic{ID: "EPIC-TST-001", State: "done"}, approved)
	if !ok {
		t.Fatal("recorded approval must produce the closing gate op")
	}
	if closedGate.Payload["state"] != "answered" || closedGate.Payload["chosen_option_keys"].([]any)[0] != "approve" {
		t.Fatalf("closed approval gate wrong: %v", closedGate.Payload)
	}

	if _, ok := BuildApprovalGateOp(Epic{ID: "EPIC-TST-002", State: "in-progress"}, "no approval here"); ok {
		t.Fatal("an epic neither awaiting nor approved gets no gate")
	}
}

func TestGateBuilderCarriesEvaluatedScopeFingerprintSeparately(t *testing.T) {
	op := BuildRQGateOp(RQ{
		ID:                        "RQ-SCOPE-1",
		Title:                     "Scoped gate",
		State:                     "decision-needed",
		EvaluatedScopeFingerprint: "scope-v7",
	})

	if got := op.Payload["evaluated_scope_fingerprint"]; got != "scope-v7" {
		t.Fatalf("evaluated scope fingerprint lost: %v", got)
	}
	if op.Payload["content_hash"] == op.Payload["evaluated_scope_fingerprint"] {
		t.Fatal("content hash and evaluated scope must remain independent")
	}
}

func TestCommitBurstFoldsClosedDaysOnly(t *testing.T) {
	commits := []Commit{
		{Hash: "c3", Date: "2026-07-28T10:00:00+03:00", Subject: "today stays out", IDs: nil},
		{Hash: "c2", Date: "2026-07-27T18:00:00+03:00", Subject: "REQ-TST-001: fix", IDs: []string{"REQ-TST-001"}},
		{Hash: "c1", Date: "2026-07-27T09:00:00+03:00", Subject: "REQ-TST-002: more", IDs: []string{"REQ-TST-002"}},
		{Hash: "c0", Date: "2026-07-26T09:00:00+03:00", Subject: "old", IDs: nil},
	}
	op, ok := BuildCommitBurstOp(commits, "2026-07-28")
	if !ok {
		t.Fatal("closed days exist — burst op expected")
	}
	events := op.Payload["events"].([]any)
	if len(events) != 2 {
		t.Fatalf("want 2 closed days, got %d", len(events))
	}
	newest := events[0].(map[string]any)
	if newest["dedupe_key"] != "commit_burst:2026-07-27" {
		t.Fatalf("days must sort newest first: %v", newest["dedupe_key"])
	}
	payload := newest["payload"].(map[string]any)
	if payload["count"] != 2 || payload["head"] != "c2" {
		t.Fatalf("burst payload wrong: %v", payload)
	}
	if len(newest["related"].([]any)) != 2 {
		t.Fatalf("related ids wrong: %v", newest["related"])
	}
	if op.Payload["external_id"] != "EVENTS-COMMITS-2026-07-28" {
		t.Fatalf("burst external id wrong: %v", op.Payload["external_id"])
	}
}

func TestExtractTracePaths(t *testing.T) {
	detail := strings.Join([]string{
		"- **Tests:** `apps/x/test/a_test.exs` (5) · `go test ./cmd`",
		"- **Code:** `tools/modernpath/cmd/factory.go` · `mix esbuild` · plain words",
	}, "\n")
	paths := ExtractTracePaths(detail)
	want := []string{"apps/x/test/a_test.exs", "tools/modernpath/cmd/factory.go"}
	if len(paths) != len(want) || paths[0] != want[0] || paths[1] != want[1] {
		t.Fatalf("trace paths wrong: %v", paths)
	}
}

func TestBuildOpsOrderAndObsoleteFilter(t *testing.T) {
	data := Data{
		Reqs: []Req{
			{ID: "REQ-TST-001", Status: "READY", Ctx: "TST"},
			{ID: "REQ-TST-009", Status: "OBSOLETE", Ctx: "TST"},
		},
		Epics: []Epic{{ID: "EPIC-TST-001", State: "in-progress"}},
		RQs: []RQ{
			{ID: "RQ-1", State: "finding", Line: 1},
			{ID: "RQ-2", State: "decision-needed", Line: 2},
		},
		OQs: []OQ{{ID: "OQ-1", Full: "q", Line: 3}},
	}
	ops := BuildOps(data, nil, "2026-07-28")
	// REQ-CROSS-222 §222.4: OBSOLETE rows sync with terminal status — the
	// pre-import skip dropped 22 terminal decisions from the store.
	if len(ops) != 5 {
		t.Fatalf("want 5 ops (2 reqs incl. OBSOLETE, 1 epic, 2 gates), got %d", len(ops))
	}
	if ops[0].Type != "upsert_requirement" || ops[2].Type != "upsert_epic" || ops[3].Type != "upsert_gate" {
		t.Fatalf("dependency order wrong: %v %v %v", ops[0].Type, ops[2].Type, ops[3].Type)
	}
	obsoleteSeen := false
	for _, op := range ops {
		if op.Payload["external_id"] == "REQ-TST-009" {
			obsoleteSeen = true
			if op.Payload["work_status"] != "OBSOLETE" {
				t.Fatalf("OBSOLETE row lost its terminal status: %v", op.Payload["work_status"])
			}
		}
		if op.Payload["external_id"] == "RQ-1" {
			t.Fatal("finding RQs must not become gates")
		}
	}
	if !obsoleteSeen {
		t.Fatal("OBSOLETE rows must sync with terminal status (REQ-CROSS-222)")
	}
}

// ---------------------------------------------------------------- epic specs (REQ-CROSS-023/024, EPIC-SYNC-006)

const speccedRecord = `# EPIC-TST-005 — Specced epic

## Specification status
SPEC-READY — awaiting the gate.

## Requirements in this epic
` + "`REQ-TST-009`" + `

## Approval
_pending_
`

func specFixtures() []EpicSpec {
	return []EpicSpec{
		{Rel: "epics/EPIC-TST-005-x/specs/architecture.md", Name: "architecture.md", Content: "# Arch"},
		{Rel: "epics/EPIC-TST-005-x/specs/requirements.md", Name: "requirements.md", Content: "# Reqs"},
	}
}

func folderEpic(state string) Epic {
	return Epic{ID: "EPIC-TST-005", State: state, Record: "epics/EPIC-TST-005-x/EPIC.md", Specs: specFixtures()}
}

func TestEpicOpSpecsPresenceRule(t *testing.T) {
	// folder-form epic: specs present, ordered, positioned
	op := BuildEpicOp(folderEpic("proposed"), speccedRecord)
	specs, ok := op.Payload["specs"].([]any)
	if !ok || len(specs) != 2 {
		t.Fatalf("folder epic must carry its specs: %v", op.Payload["specs"])
	}
	first := specs[0].(map[string]any)
	if first["external_id"] != "epics/EPIC-TST-005-x/specs/architecture.md" ||
		first["name"] != "architecture.md" || first["position"] != 1 || first["content_md"] != "# Arch" {
		t.Fatalf("spec item shape wrong: %v", first)
	}

	// folder-form with no specs: present-empty (archives server-side)
	empty := BuildEpicOp(Epic{ID: "EPIC-TST-006", Record: "epics/EPIC-TST-006-y/EPIC.md"}, "# EPIC-TST-006 — Empty")
	if v, has := empty.Payload["specs"]; !has {
		t.Fatal("folder epic without specs must carry present-empty specs")
	} else if len(v.([]any)) != 0 {
		t.Fatalf("expected empty specs, got %v", v)
	}

	// file-form epic: key absent (never touches server artifacts)
	file := BuildEpicOp(Epic{ID: "EPIC-TST-001", Record: "epics/EPIC-TST-001.md"}, epicRecord)
	if _, has := file.Payload["specs"]; has {
		t.Fatal("file-form epic must not carry a specs key")
	}
}

func TestEpicOpSpecContentCapped(t *testing.T) {
	big := strings.Repeat("a", 70000)
	epic := Epic{ID: "EPIC-TST-007", Record: "epics/EPIC-TST-007-z/EPIC.md",
		Specs: []EpicSpec{{Rel: "epics/EPIC-TST-007-z/specs/requirements.md", Name: "requirements.md", Content: big}}}
	op := BuildEpicOp(epic, "# EPIC-TST-007 — Big")
	content := op.Payload["specs"].([]any)[0].(map[string]any)["content_md"].(string)
	if len(content) != 65536 {
		t.Fatalf("spec content must cap at 65536, got %d", len(content))
	}
}

func TestSpecApprovalLineClassification(t *testing.T) {
	cases := []struct {
		text, want string
	}{
		{speccedRecord, "ready"},
		{strings.Replace(speccedRecord, "SPEC-READY — awaiting the gate.", "SPEC-DRAFT — writing.", 1), "draft"},
		{strings.Replace(speccedRecord, "SPEC-READY — awaiting the gate.", "SPEC-APPROVED — reviewed · USER:2026-08-05", 1), "approved"},
		// APPROVED without a USER tag is NOT an approval (honesty rule)
		{strings.Replace(speccedRecord, "SPEC-READY — awaiting the gate.", "SPEC-APPROVED — someone said ok", 1), "ready"},
		{epicRecord, ""}, // no section = legacy
		{"## Specification status\nThe specs live in specs/ and are prose.\n", ""}, // section, no marker = legacy
	}
	for i, c := range cases {
		if got, _ := SpecApprovalLineOf(c.text); got != c.want {
			t.Fatalf("case %d: want %q, got %q", i, c.want, got)
		}
	}
}

func TestSpecApprovalGateOpenAnsweredAndLegacyForms(t *testing.T) {
	// SPEC-READY + specs → open gate holding the epic
	openGate, ok := BuildSpecApprovalGateOp(folderEpic("proposed"), speccedRecord)
	if !ok {
		t.Fatal("SPEC-READY folder epic with specs must gate")
	}
	p := openGate.Payload
	if p["external_id"] != "SPEC-APPROVE-EPIC-TST-005" || p["kind"] != "spec_approval" || p["state"] != "open" {
		t.Fatalf("open spec gate wrong: %v", p)
	}
	holds := p["holds"].([]any)
	if len(holds) != 1 || holds[0].(map[string]any)["held_external_id"] != "EPIC-TST-005" ||
		holds[0].(map[string]any)["held_entity_type"] != "epic" {
		t.Fatalf("spec gate must hold the epic: %v", holds)
	}
	if body := p["body_md"].(string); !strings.Contains(body, "architecture.md") {
		t.Fatalf("body must index the specs: %q", body)
	}

	// SPEC-APPROVED … USER: → answered form
	approved := strings.Replace(speccedRecord, "SPEC-READY — awaiting the gate.",
		"SPEC-APPROVED — reviewed and accepted · USER:2026-08-05 (SPEC-APPROVE-EPIC-TST-005)", 1)
	closedGate, ok := BuildSpecApprovalGateOp(folderEpic("in-progress"), approved)
	if !ok {
		t.Fatal("SPEC-APPROVED must produce the answered gate op")
	}
	if closedGate.Payload["state"] != "answered" || closedGate.Payload["source_tag"] != "USER:2026-08-05" ||
		closedGate.Payload["chosen_option_keys"].([]any)[0] != "approve" {
		t.Fatalf("answered spec gate wrong: %v", closedGate.Payload)
	}

	// SPEC-DRAFT: no gate
	draft := strings.Replace(speccedRecord, "SPEC-READY — awaiting the gate.", "SPEC-DRAFT — writing.", 1)
	if _, ok := BuildSpecApprovalGateOp(folderEpic("proposed"), draft); ok {
		t.Fatal("SPEC-DRAFT must not gate")
	}

	// legacy (no marker) and file-form epics: no gate
	if _, ok := BuildSpecApprovalGateOp(Epic{ID: "EPIC-TST-001", Record: "epics/EPIC-TST-001.md"}, epicRecord); ok {
		t.Fatal("legacy epic must not gate")
	}

	// SPEC-READY but no specs: no gate (an approval over nothing is dishonest)
	noSpecs := Epic{ID: "EPIC-TST-005", Record: "epics/EPIC-TST-005-x/EPIC.md"}
	if _, ok := BuildSpecApprovalGateOp(noSpecs, speccedRecord); ok {
		t.Fatal("SPEC-READY with no specs must not gate")
	}
}

// REQ-PLN-054 / D-MC-6 (USER:2026-08-07): a requirement's one-line description
// comes from its detail block's **Statement:** line; where the ledger has none
// (~69% of rows at decision time) it falls back to the first criterion's THEN
// clause — the outcome half reads as a summary where the full GWT does not.
// Neither present → empty (never invent one).
func TestParseDescriptionPrefersStatementThenFallsBackToThen(t *testing.T) {
	withStatement := "- **Status:** DONE\n- **Statement:** The face shows every model we can call.\n" +
		"- **Acceptance criteria:**\n  - GIVEN a user WHEN it loads THEN the catalog renders.\n"
	if got := ParseDescription(withStatement); got != "The face shows every model we can call." {
		t.Fatalf("statement not used: %q", got)
	}

	criteriaOnly := "- **Status:** DONE\n- **Acceptance criteria:**\n" +
		"  - GIVEN a batch WHEN applied THEN the release row exists and every row carries its id.\n"
	if got := ParseDescription(criteriaOnly); got != "The release row exists and every row carries its id." {
		t.Fatalf("THEN fallback wrong: %q", got)
	}

	if got := ParseDescription("- **Status:** DONE\n- **Tests:** —\n"); got != "" {
		t.Fatalf("expected empty, got %q", got)
	}
	if got := ParseDescription(""); got != "" {
		t.Fatalf("expected empty for no detail, got %q", got)
	}
}

// REQ-PLN-054 / TASK-MC-107: an epic's description is its "## User outcome"
// section — first paragraph, folded to one line. 34 of 139 records have no
// such heading; those carry no description rather than an invented one, so the
// key is absent from the payload (and their content hashes do not move).
func TestParseEpicDescriptionUsesUserOutcomeSection(t *testing.T) {
	record := "# EPIC-MC-001 — Scope face\n\n- **Status:** IN_REVIEW\n\n" +
		"## User outcome (UR-MC-001)\nSomeone opening the scope face sees\nthe entire ledger at once.\n\n" +
		"A second paragraph that is not the summary.\n\n## Decisions\n| ID | Q |\n"
	want := "Someone opening the scope face sees the entire ledger at once."
	if got := ParseEpicDescription(record); got != want {
		t.Fatalf("user outcome not folded to one line:\n  got:  %q\n  want: %q", got, want)
	}

	if got := ParseEpicDescription("# EPIC-X — No outcome\n\n## Tasks\n- TASK-1\n"); got != "" {
		t.Fatalf("expected empty without the heading, got %q", got)
	}

	op := BuildEpicOp(Epic{ID: "EPIC-X", Record: "epics/EPIC-X.md"}, "# EPIC-X — t\n\n## Tasks\n- a\n")
	if _, present := op.Payload["description"]; present {
		t.Fatal("description key must be absent when there is no user outcome")
	}
}

// REQ-CROSS-028 / SCN-SY-060+061: an epic's loop state is recorded in
// WORKLIST's own "Upper status" / "Lower status" columns (127 of 146 rows carry
// both) and was thrown away — only the Overall cell was read, to decide whether
// to open an approval gate. `initiatives.status` is NOT the target: it is the
// board column, which SERVER-SYNC-DESIGN §1.3 marks "untouched" and Core.Sync
// refuses to overwrite ("moving cards is the board's job").
func TestBuildEpicOpCarriesWorklistLoopStatuses(t *testing.T) {
	epic := Epic{
		ID:     "EPIC-X-001",
		Record: "epics/EPIC-X-001.md",
		Upper:  "UPPER_VALIDATED (live browser pass)",
		Lower:  "LOWER_VERIFIED",
	}
	p := BuildEpicOp(epic, "# EPIC-X-001 — t\n").Payload
	if p["upper_loop_status"] != "UPPER_VALIDATED (live browser pass)" {
		t.Fatalf("upper loop status not carried: %v", p["upper_loop_status"])
	}
	if p["lower_loop_status"] != "LOWER_VERIFIED" {
		t.Fatalf("lower loop status not carried: %v", p["lower_loop_status"])
	}
	if _, present := p["status"]; present {
		t.Fatal("must not send a board status — sync never moves cards (SERVER-SYNC-DESIGN §1.3)")
	}

	// An empty or em-dash cell is absence, not a status: the key stays off the
	// payload so those epics' content hashes do not move.
	bare := BuildEpicOp(Epic{ID: "EPIC-X-002", Record: "epics/EPIC-X-002.md", Upper: "—", Lower: ""}, "# EPIC-X-002 — t\n").Payload
	if _, present := bare["upper_loop_status"]; present {
		t.Fatal("em-dash must not sync as a status")
	}
	if _, present := bare["lower_loop_status"]; present {
		t.Fatal("empty cell must not sync as a status")
	}
}

// REQ-CROSS-028 / SCN-SY-062+063: SCN tables become scenario-kind criteria.
// The server has accepted them since M4 (Core.Sync passes payload `scenarios`
// through sync_criteria with owner :epic_id) — no builder ever sent any.
// Six header shapes exist across the records, so the text column is chosen by
// header name where recognizable and by longest cell otherwise.
func TestParseScenariosAcrossHeaderShapes(t *testing.T) {
	cases := []struct{ name, section, wantID, wantText string }{
		{
			name: "SCN | Summary | Status",
			section: "## BDD acceptance scenarios (SCN — upper loop)\n" +
				"| SCN | Summary | Status |\n|---|---|---|\n" +
				"| SCN-SY-001 | Selecting a system re-queries with the id. | LOWER_VERIFIED |\n",
			wantID: "SCN-SY-001", wantText: "Selecting a system re-queries with the id.",
		},
		{
			name: "Scenario | Requirement | Statement | Status — the id column is not the text column",
			section: "## Acceptance scenarios\n" +
				"| Scenario | Requirement | Statement | Status |\n|---|---|---|---|\n" +
				"| SCN-SY-041 | REQ-CROSS-017 | GIVEN a batch WHEN applied THEN the release exists | DONE |\n",
			wantID: "SCN-SY-041", wantText: "GIVEN a batch WHEN applied THEN the release exists",
		},
		{
			name: "Scenario | Summary | Failing evidence | Passing evidence — evidence cells must not win",
			section: "## BDD acceptance scenarios\n" +
				"| Scenario | Summary | Failing evidence | Passing evidence |\n|---|---|---|---|\n" +
				"| SCN-RK-001 | The risk form offers all ten fields. | RED core 5/5; RED FE 3/3 with a very long trailing evidence note that is longer than the summary | core 5/5; FE 3/3 |\n",
			wantID: "SCN-RK-001", wantText: "The risk form offers all ten fields.",
		},
	}
	for _, c := range cases {
		got := ParseScenarios("# EPIC-T — t\n\n"+c.section+"\n## Next\n", "EPIC-T")
		if len(got) != 1 {
			t.Fatalf("%s: expected 1 scenario, got %d", c.name, len(got))
		}
		s := got[0].(map[string]any)
		// Owner-namespaced, like requirement criteria (REQ-CMP-010#AC1): SCN ids
		// are scoped by AREA, not by epic — 85 prefixes across the records — so
		// two epics in one area legitimately reach for the same SCN id.
		if s["external_id"] != "EPIC-T#"+c.wantID {
			t.Errorf("%s: id = %v, want EPIC-T#%s", c.name, s["external_id"], c.wantID)
		}
		if s["kind"] != "scenario" {
			t.Errorf("%s: kind = %v, want scenario", c.name, s["kind"])
		}
		text, _ := s["statement"].(string)
		if g, ok := s["given"].(string); ok {
			text = "GIVEN " + g + " WHEN " + s["when"].(string) + " THEN " + s["then"].(string)
		}
		if text != c.wantText {
			t.Errorf("%s:\n  got  %q\n  want %q", c.name, text, c.wantText)
		}
	}

	// 26 records carry the heading with no table beneath it: no scenarios, and
	// no `scenarios` key on the payload, so their hashes do not move.
	if got := ParseScenarios("# E — t\n\n## Acceptance scenarios\n_pending_\n", "E"); len(got) != 0 {
		t.Fatalf("headingless-table must yield no scenarios, got %d", len(got))
	}
	if _, present := BuildEpicOp(Epic{ID: "E", Record: "epics/E.md"}, "# E — t\n").Payload["scenarios"]; present {
		t.Fatal("no scenarios must mean no key (hash stability)")
	}
}

// A heading merely CONTAINING "acceptance scenarios" is not the scenario
// section: "## Deferred acceptance scenarios (out of scope)" answers a
// different question, and first-match would sync its rows as the epic's
// scenarios while the real section below is never read. The tolerated
// prefixes are the ones records actually write — bare, "BDD", "SCN —",
// "SCN — BDD", "Journeys and" — and an unknown prefix yields NO scenarios
// (visible in sync) rather than the wrong ones (invisible).
func TestADecoratedNonScenarioHeadingDoesNotHijackTheSection(t *testing.T) {
	record := "# EPIC-T — t\n\n" +
		"## Deferred acceptance scenarios (out of scope)\n" +
		"| SCN | Summary | Status |\n|---|---|---|\n" +
		"| SCN-TST-900 | Deferred to the next release. | DEFERRED |\n" +
		"\n## Acceptance scenarios\n" +
		"| SCN | Summary | Status |\n|---|---|---|\n" +
		"| SCN-TST-001 | The real observable outcome. | UPPER_VALIDATED |\n" +
		"\n## Next\n"
	got := ParseScenarios(record, "EPIC-T")
	if len(got) != 1 {
		t.Fatalf("expected the real section's 1 scenario, got %d", len(got))
	}
	if id := got[0].(map[string]any)["external_id"]; id != "EPIC-T#SCN-TST-001" {
		t.Fatalf("the deferred table hijacked the parse: got %v", id)
	}
}

// The prefix rule alone leaves the suffix as the same hijack surface: a
// heading suffixed "(deferred/out of scope)" above the real section is matched
// first and its rows sync as the epic's scenarios while the real section is
// never read. The suffix is the same kind of alternation as the prefix — the
// qualifiers records actually write, and nothing wider.
func TestASuffixedNonScenarioHeadingDoesNotHijackTheSection(t *testing.T) {
	record := "# EPIC-T — t\n\n" +
		"## Acceptance scenarios (deferred/out of scope)\n" +
		"| SCN | Summary | Status |\n|---|---|---|\n" +
		"| SCN-TST-900 | Deferred to the next release. | DEFERRED |\n" +
		"\n## Acceptance scenarios\n" +
		"| SCN | Summary | Status |\n|---|---|---|\n" +
		"| SCN-TST-001 | The real observable outcome. | UPPER_VALIDATED |\n" +
		"\n## Next\n"
	got := ParseScenarios(record, "EPIC-T")
	if len(got) != 1 {
		t.Fatalf("expected the real section's 1 scenario, got %d", len(got))
	}
	if id := got[0].(map[string]any)["external_id"]; id != "EPIC-T#SCN-TST-001" {
		t.Fatalf("the suffixed table hijacked the parse: got %v", id)
	}
}

// Guard, expected green: every prefix shape the corpus and template write.
func TestEveryRealScenarioHeadingPrefixStillParses(t *testing.T) {
	for _, heading := range []string{
		"## Acceptance scenarios",
		"## BDD acceptance scenarios",
		"## BDD acceptance scenarios (SCN — upper loop)",
		"## BDD acceptance scenarios (outline — sharpened at build)",
		"## BDD acceptance scenarios (outline — sharpened at SPEC-READY)",
		"## SCN — acceptance scenarios",
		"## SCN — BDD acceptance scenarios (upper loop)",
		"## Journeys and acceptance scenarios",
	} {
		record := "# EPIC-T — t\n\n" + heading + "\n" +
			"| SCN | Summary | Status |\n|---|---|---|\n" +
			"| SCN-TST-001 | An outcome. | READY |\n\n## Next\n"
		if got := ParseScenarios(record, "EPIC-T"); len(got) != 1 {
			t.Errorf("%q: expected 1 scenario, got %d", heading, len(got))
		}
	}
}

// REQ-CROSS-028 follow-up (USER:2026-08-07): two DIFFERENT epics in the same
// area share an SCN id — SCN-AK-001 belongs to both EPIC-FE-034 ("API keys:
// least-privilege scope selection") and EPIC-PORTFOLIO-038 ("API key
// management"). acceptance_criteria.external_id is unique per tenant, so the
// second sync stole the row and 9 epics served zero scenarios. Owner-namespacing
// makes the collision impossible by construction rather than by convention.
func TestScenarioIDsAreNamespacedByTheirEpic(t *testing.T) {
	section := "## Acceptance scenarios\n| SCN | Summary | Status |\n|---|---|---|\n" +
		"| SCN-AK-001 | The key form offers every scope. | DONE |\n"

	a := BuildEpicOp(Epic{ID: "EPIC-FE-034", Record: "epics/EPIC-FE-034.md"}, "# EPIC-FE-034 — t\n\n"+section)
	b := BuildEpicOp(Epic{ID: "EPIC-PORTFOLIO-038", Record: "epics/EPIC-PORTFOLIO-038.md"}, "# EPIC-PORTFOLIO-038 — t\n\n"+section)

	idOf := func(op Op) string {
		return op.Payload["scenarios"].([]any)[0].(map[string]any)["external_id"].(string)
	}
	if idOf(a) == idOf(b) {
		t.Fatalf("two epics must not claim one criterion row: both got %q", idOf(a))
	}
	if idOf(a) != "EPIC-FE-034#SCN-AK-001" {
		t.Errorf("id = %q, want EPIC-FE-034#SCN-AK-001", idOf(a))
	}
	if idOf(b) != "EPIC-PORTFOLIO-038#SCN-AK-001" {
		t.Errorf("id = %q, want EPIC-PORTFOLIO-038#SCN-AK-001", idOf(b))
	}
}

// REQ-CROSS-031: the generic RDD framework puts a context's ledger at
// libs/<ctx>/REQUIREMENTS.md — context in the DIRECTORY — while this workspace
// uses tasks/<CTX>-REQUIREMENTS.md. Only the second was accepted, so the first
// real client repository had all 19 of its ledgers skipped and synced 0 ops.
// Both layouts are the documented convention; both must parse.
func TestParseLedgerAcceptsDirectoryScopedContext(t *testing.T) {
	body := "## Dashboard — BNK\nTotals: 1 DONE\n\n" +
		"| ID | Title | Stage | Status | Source | Tests | Code |\n|--|--|--|--|--|--|--|\n" +
		"| REQ-BNK-001 | Statement ingestion | P | DONE | x | t | c |\n"

	for _, path := range []string{
		"tasks/BNK-REQUIREMENTS.md", // this workspace
		"libs/bnk/REQUIREMENTS.md",  // the generic framework
		"libs/BNK/REQUIREMENTS.md",  // either case
	} {
		reqs := ParseLedger(path, body)
		if len(reqs) != 1 {
			t.Fatalf("%s: expected 1 requirement, got %d", path, len(reqs))
		}
		if reqs[0].Ctx != "BNK" {
			t.Errorf("%s: context = %q, want BNK", path, reqs[0].Ctx)
		}
		if reqs[0].ID != "REQ-BNK-001" {
			t.Errorf("%s: id = %q", path, reqs[0].ID)
		}
	}

	// A bare REQUIREMENTS.md with no context directory is still skipped — there
	// is nothing to derive a context from, and guessing would mislabel rows.
	if reqs := ParseLedger("REQUIREMENTS.md", body); reqs != nil {
		t.Errorf("a context-less REQUIREMENTS.md must be skipped, got %d", len(reqs))
	}
}

// REQ-CROSS-031: a markdown table cell may contain an escaped pipe. Splitting
// naively on "|" shifts every column after it, so a requirement whose TITLE
// contains \|difference\| had prose parsed as its work_status and the server
// rejected the whole batch at op 285 — after 284 had already applied.
func TestSplitCellsRespectsEscapedPipes(t *testing.T) {
	line := `| REQ-AP-103 | Reduces \|difference\| toward zero | A4 | DONE | src | t | c |`
	cells := splitCells(line)
	if len(cells) < 5 {
		t.Fatalf("too few cells: %d (%q)", len(cells), cells)
	}
	if cells[1] != "REQ-AP-103" {
		t.Errorf("id cell = %q", cells[1])
	}
	if cells[2] != "Reduces |difference| toward zero" {
		t.Errorf("title cell = %q — the escape should be resolved, not split on", cells[2])
	}
	if cells[4] != "DONE" {
		t.Errorf("status cell = %q, want DONE — columns shifted", cells[4])
	}
}

// REQ-CROSS-031: a ledger's status cell carries the vocabulary term, sometimes
// with a human qualifier or markdown emphasis around it — "DONE (DEMO-GRADE)",
// "**DONE**". The term is what the contract validates; the qualifier is prose
// that belongs to the ledger. Sending the whole cell got the batch rejected at
// op 1363 with 1362 already applied.
func TestParseLedgerNormalisesQualifiedStatuses(t *testing.T) {
	rows := map[string]string{
		"DONE (DEMO-GRADE)":             "DONE",
		"**DONE**":                      "DONE",
		"DEFERRED — waiting on GAP-009": "DEFERRED",
		"IN_REVIEW":                     "IN_REVIEW",
	}
	for cell, want := range rows {
		body := "## Dashboard — TAX\nTotals: 1 DONE\n\n| ID | Title | Stage | Status |\n|--|--|--|--|\n" +
			"| REQ-TAX-001 | a thing | F1 | " + cell + " |\n"
		reqs := ParseLedger("libs/tax/REQUIREMENTS.md", body)
		if len(reqs) != 1 {
			t.Fatalf("%q: expected 1 requirement, got %d", cell, len(reqs))
		}
		if reqs[0].Status != want {
			t.Errorf("%q → status %q, want %q", cell, reqs[0].Status, want)
		}
	}
}

// REQ-CROSS-031: a bounded-context code may contain a digit — one real ledger has E2E.
// The id patterns required [A-Z]+, so EPIC-E2E-001 matched nothing and its
// work-list row was skipped in silence.
func TestContextCodesMayContainDigits(t *testing.T) {
	reqs := ParseLedger("libs/e2e/REQUIREMENTS.md",
		"## Dashboard — E2E\nTotals: 1 DONE\n\n| ID | Title | Stage | Status |\n|--|--|--|--|\n"+
			"| REQ-E2E-001 | a journey | P | DONE |\n")
	if len(reqs) != 1 || reqs[0].Ctx != "E2E" {
		t.Fatalf("digit-bearing context not parsed: %+v", reqs)
	}
	epics := ParseWorklist(
		"| EPIC-E2E-001 | [r](epics/EPIC-E2E-001.md) | u | s | s | t | U | L | **DONE** | — | n |\n",
		[]string{"EPIC-E2E-001.md"}, map[string]bool{})
	if len(epics) != 1 || epics[0].ID != "EPIC-E2E-001" {
		t.Fatalf("digit-bearing epic id not parsed: %+v", epics)
	}
}

// REQ-CROSS-032: two open-question table layouts are in real use.
//
//	ours   | ID | Question | Owner | Blocking | See also |        question in col 2, ✅ marks resolved
//	theirs | ID | Source | Question | Category | Owner | Blocking | Status |   question in col 3, **RESOLVED**
//
// The parser assumed ours: it read column 2 as the question and only looked for
// ✅/"done". Against theirs it would have published 61 source-doc references as
// the questions, and treated resolved rows as open. Its id pattern (OQ-\w+) also
// could not match OQ-UI-Q1, so in practice it matched nothing at all.
func TestParseOpenQuestionsHandlesBothTableLayouts(t *testing.T) {
	ours := "| ID | Question | Owner | Blocking | See also |\n|--|--|--|--|--|\n" +
		"| OQ-001 | **Deployment topology.** Which cloud? | TL | P1 | — |\n" +
		"| OQ-002 | **Realtime transport.** Which protocol? | TL | ✅ RES-3 | — |\n"
	got := ParseOpenQuestions(ours)
	if len(got) != 2 {
		t.Fatalf("ours: expected 2, got %d", len(got))
	}
	if !strings.Contains(got[0].Full, "Which cloud?") {
		t.Errorf("ours: question = %q", got[0].Full)
	}
	if got[0].Resolved || !got[1].Resolved {
		t.Errorf("ours: resolved flags wrong: %v %v", got[0].Resolved, got[1].Resolved)
	}

	theirs := "| ID | Source | Question | Category | Owner | Blocking | Status |\n|--|--|--|--|--|--|--|\n" +
		"| OQ-UI-Q5 | `docs/06` §5.6 | Bulk-approval ergonomics over an approval set? | DOM | PO | REQ-WBX-002 | **OPEN** — per-screen |\n" +
		"| OQ-UI-Q7 | `docs/06` §4.2 | Status-ribbon responsive collapse behavior? | TECH | TL | FE | **RESOLVED** 2026-06-23 |\n"
	got = ParseOpenQuestions(theirs)
	if len(got) != 2 {
		t.Fatalf("theirs: expected 2, got %d — hyphenated ids must parse", len(got))
	}
	if got[0].ID != "OQ-UI-Q5" {
		t.Errorf("theirs: id = %q", got[0].ID)
	}
	if !strings.Contains(got[0].Full, "Bulk-approval ergonomics") {
		t.Errorf("theirs: took the wrong column as the question: %q", got[0].Full)
	}
	if got[0].Resolved || !got[1].Resolved {
		t.Errorf("theirs: resolved flags wrong: %v %v", got[0].Resolved, got[1].Resolved)
	}
}

// REQ-CROSS-034: a gap register is a decision surface too. One real register holds 30
// rows — 11 OPEN, 3 DECISION-NEEDED — and none of them reached the queue,
// because the parser only recognised OQ ids. A capability gap nobody has
// decided on is exactly the thing Your move exists to show.
func TestParseOpenQuestionsAcceptsGapRegisterRows(t *testing.T) {
	doc := "| ID | Gap | Owner | Status |\n|--|--|--|--|\n" +
		"| GAP-010 | **Asunto-Oy module** — vastikelaskenta and friends | AR+ACC | DECISION-NEEDED |\n" +
		"| GAP-012 | **Something already specced** | ACC | **RESOLVED-IN-SPEC** (INV-ACC-012) |\n"
	got := ParseOpenQuestions(doc)
	if len(got) != 2 {
		t.Fatalf("expected 2 gap rows, got %d", len(got))
	}
	if got[0].ID != "GAP-010" {
		t.Errorf("id = %q", got[0].ID)
	}
	if !strings.Contains(got[0].Full, "Asunto-Oy") {
		t.Errorf("question cell = %q", got[0].Full)
	}
	if got[0].Resolved {
		t.Error("a DECISION-NEEDED gap is open, not resolved")
	}
	if !got[1].Resolved {
		t.Error("RESOLVED-IN-SPEC must count as resolved")
	}
}

// REQ-CROSS-032 follow-up: the longest cell is NOT always the question. A real
// table has "| ID | Source | Question | Cat | Owner | Blocking for | Suggested
// default |", and the Suggested-default note is routinely longer than the
// question it answers — so Mission Control published 60 of them as the
// questions, each starting "*Suggested default:*". The header names the column;
// use it, and fall back to longest only when there is no usable header.
func TestParseOpenQuestionsPrefersTheHeaderNamedQuestionColumn(t *testing.T) {
	doc := "| ID | Source | Question | Cat | Owner | Blocking for | Suggested default |\n" +
		"|--|--|--|--|--|--|--|\n" +
		"| OQ-048 | `domain/16` KYC §12.2 | Person-level dedup across customers' KYC files? | TECH | TL | P5 | " +
		"*Suggested default:* strict per-file isolation in v1 (simpler privacy posture); revisit with monitoring evidence. |\n"

	got := ParseOpenQuestions(doc)
	if len(got) != 1 {
		t.Fatalf("expected 1, got %d", len(got))
	}
	if !strings.Contains(got[0].Full, "Person-level dedup") {
		t.Errorf("took the wrong column: %q", got[0].Full)
	}
	if strings.Contains(got[0].Full, "Suggested default") {
		t.Errorf("published the suggested default as the question: %q", got[0].Full)
	}
}

// REQ-PLN-059: the answer is in the document. Having stopped publishing the
// suggested default AS the question, the extractor then threw it away entirely
// — 79 questions reached Mission Control with no recommendation, no options and
// a body identical to the title, so the only honest move on that screen was to
// go read the source doc. The default is the author's recommendation; it rides
// as one.
func TestParseOpenQuestionsCarriesTheSuggestedDefaultAsARecommendation(t *testing.T) {
	doc := "| ID | Source | Question | Cat | Owner | Blocking for | Status |\n" +
		"|--|--|--|--|--|--|--|\n" +
		"| OQ-UI-Q5 | `docs/06` §5.6 | Bulk-approval ergonomics over an approval set? | DOM | PO | **REQ-WBX-002** | " +
		"**OPEN** — rides until the Approvals inbox is designed. *Suggested default:* bulk-confirm over " +
		"confidence-sorted selections; never bulk-approve CRITICAL without per-item step-up. |\n"

	got := ParseOpenQuestions(doc)
	if len(got) != 1 {
		t.Fatalf("expected 1, got %d", len(got))
	}
	if !strings.Contains(got[0].Suggested, "bulk-confirm over confidence-sorted") {
		t.Errorf("suggested default not carried: %q", got[0].Suggested)
	}
	if strings.Contains(got[0].Suggested, "Suggested default") {
		t.Errorf("kept the label instead of the answer: %q", got[0].Suggested)
	}
	if strings.Contains(got[0].Suggested, "OPEN") {
		t.Errorf("swallowed the status prose ahead of it: %q", got[0].Suggested)
	}

	op := BuildOQGateOp(got[0])
	rec, _ := op.Payload["recommendation"].(string)
	if !strings.Contains(rec, "bulk-confirm over confidence-sorted") {
		t.Errorf("gate carries no recommendation: %q", rec)
	}
}

// A question with no suggested default must not grow an empty recommendation —
// "recommendation attached" on a gate that has none is a worse lie than none.
func TestOQGateOmitsAnAbsentRecommendation(t *testing.T) {
	doc := "| ID | Question |\n|--|--|\n| OQ-101 | Does the ledger own release membership? |\n"
	got := ParseOpenQuestions(doc)
	if len(got) != 1 {
		t.Fatalf("expected 1, got %d", len(got))
	}
	if _, ok := BuildOQGateOp(got[0]).Payload["recommendation"]; ok {
		t.Error("emitted a recommendation key for a question that has none")
	}
}

// REQ-CROSS-032 follow-up: a manifest may map several files to one document
// type. Only files[0] was read, so mapping a gap register alongside an
// open-questions inventory silently stopped parsing the inventory — its 54
// gates stayed on the server frozen at whatever text they had when last seen,
// and no error said so.
func TestSnapshotReadsEveryMappedOpenQuestionFile(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "docs"), 0o755); err != nil {
		t.Fatal(err)
	}
	write := func(rel, body string) {
		if err := os.WriteFile(filepath.Join(root, rel), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("docs/05-gap-register.md", "| ID | Gap | Status |\n|--|--|--|\n| GAP-010 | A capability gap | OPEN |\n")
	write("docs/08-open-questions.md", "| ID | Question | Owner |\n|--|--|--|\n| OQ-048 | A real question? | TL |\n")
	if err := os.MkdirAll(filepath.Join(root, ".modernpath"), 0o755); err != nil {
		t.Fatal(err)
	}
	write(".modernpath/manifest.json", `{"schema_version":1,"documents":{"open_questions":{"paths":["docs/08-open-questions.md","docs/05-gap-register.md"],"format":"rdd-open-questions-v1"}}}`)

	m, _, err := manifest.Load(root)
	if err != nil {
		t.Fatal(err)
	}
	data, _ := Snapshot(root, m)

	ids := map[string]bool{}
	for _, o := range data.OQs {
		ids[o.ID] = true
	}
	if !ids["OQ-048"] || !ids["GAP-010"] {
		t.Fatalf("both mapped files must be parsed, got %v", ids)
	}
}

// REQ-CROSS-072 (`RUN:2026-08-13`, seen in the drawer on beta): the citation
// splitter treated a bare comma as a separator, so every citation carrying a
// comma inside parentheses or quotes was shredded. REQ-PLN-055's sources
// rendered as four fragments — `1`, `446 rows synced`, `all base)` and
// `USER:2026-08-08 ("your move is empty` — which is the same unreadable-sources
// complaint REQ-CROSS-059 fixed, arriving from the extractor side.
func TestCitationsAreNotSplitInsideParensOrQuotes(t *testing.T) {
	cases := []struct {
		name   string
		source string
		want   []string
	}{
		{
			name:   "a thousands separator is not a citation boundary",
			source: "`RUN:2026-08-08` (client repo: 1,446 rows synced, all base)",
			want:   []string{"RUN:2026-08-08 (client repo: 1,446 rows synced, all base)"},
		},
		{
			name:   "a comma inside a quoted user phrase is not a boundary",
			source: `USER:2026-08-08 ("your move is empty, as is whole")`,
			want:   []string{`USER:2026-08-08 ("your move is empty, as is whole")`},
		},
		{
			name:   "the interpunct still separates",
			source: "`USER:2026-08-08` · `RUN:2026-08-08` (a, b) · `DOC:docs/07.md`",
			want:   []string{"USER:2026-08-08", "RUN:2026-08-08 (a, b)", "DOC:docs/07.md"},
		},
		{
			name:   "a top-level comma still separates, so older ledgers keep working",
			source: "`USER:2026-08-08`, `DOC:docs/07.md`",
			want:   []string{"USER:2026-08-08", "DOC:docs/07.md"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := ParseCitations(tc.source)
			if len(got) != len(tc.want) {
				t.Fatalf("got %d citations, want %d: %#v", len(got), len(tc.want), got)
			}
			for i, w := range tc.want {
				ref := got[i].(map[string]any)["ref"].(string)
				if ref != w {
					t.Errorf("citation %d = %q, want %q", i, ref, w)
				}
			}
		})
	}
}

// REQ-CROSS-073 (`RUN:2026-08-13`): a third declaration shape. 52 user
// requirements — the whole EPIC-PORTFOLIO-* family — declare themselves in a
// `## Linked user requirements` table, which the parser could not read. The
// consequence was not cosmetic: their requirements' UR column named a parent
// the platform had no entity for, so ~100 requirements stayed orphans in the
// compliance matrix and no `derives` trace could ever be built for them.
func TestEpicUserRequirementFromLinkedTable(t *testing.T) {
	record := `# EPIC-PORTFOLIO-038 - API key management

## User outcome
A workspace admin can create an API key for programmatic access — seeing the raw key **once** — list the keys they have, and revoke one.

## Linked user requirements
| UR | Statement | Status |
|---|---|---|
| UR-PORTFOLIO-038 | The system shall let a user list, create (one-time raw reveal) and revoke the tenant's API keys, never exposing the key hash. | IN_PROGRESS |

## Requirements realized
- **REQ-PLT-007** — API key management.
`
	ur, ok := ParseEpicUserRequirement(record)
	if !ok {
		t.Fatal("the linked-user-requirements table was not read at all")
	}
	if ur.ID != "UR-PORTFOLIO-038" {
		t.Errorf("id = %q, want UR-PORTFOLIO-038", ur.ID)
	}
	if !strings.Contains(ur.Statement, "one-time raw reveal") {
		t.Errorf("statement did not come from the table row: %q", ur.Statement)
	}
}

// The prose heading must still win where both are present — it is the shape the
// skill writes, and it carries the fuller statement.
func TestEpicUserRequirementPrefersTheDeclaredHeading(t *testing.T) {
	record := `# EPIC-SY-010 — epics carry their state

## User outcome (UR-SY-010)
An epic's real state and its acceptance scenarios are visible in the app.

## Linked user requirements
| UR | Statement | Status |
|---|---|---|
| UR-OTHER-999 | Something else entirely. | TODO |
`
	ur, ok := ParseEpicUserRequirement(record)
	if !ok {
		t.Fatal("the heading shape stopped parsing")
	}
	if ur.ID != "UR-SY-010" {
		t.Errorf("id = %q, want UR-SY-010 — the table must not override the heading", ur.ID)
	}
}

// A table that is not the user-requirements table must not be mined for URs.
func TestEpicUserRequirementIgnoresUnrelatedTables(t *testing.T) {
	record := `# EPIC-X-001 — something

## Source material
| Source id | Type | Reference | Notes |
|---|---|---|---|
| UR-NOPE-001 | doc | somewhere.md | not a declaration |
`
	if _, ok := ParseEpicUserRequirement(record); ok {
		t.Fatal("a UR was mined out of an unrelated table")
	}
}

// REQ-CROSS-073, fourth shape: `- **User outcome (UR-SYNC-005):** <statement>`
// — a bullet with the colon INSIDE the bold. Nine user requirements declare
// themselves this way (the EPIC-SYNC-* and EPIC-INT-* families), and they are
// precisely the parents the CROSS ledger's UR column names most often.
func TestEpicUserRequirementFromBulletOutcome(t *testing.T) {
	record := `# EPIC-SYNC-005 — release scoping

## Scope
- **User outcome (UR-SYNC-005):** Work is scoped to a named release. The team selects the current release once, and sync stamps everything to it.
- **Blast radius:** the sync payload.
`
	ur, ok := ParseEpicUserRequirement(record)
	if !ok {
		t.Fatal("the bullet outcome shape was not read at all")
	}
	if ur.ID != "UR-SYNC-005" {
		t.Errorf("id = %q, want UR-SYNC-005", ur.ID)
	}
	if !strings.Contains(ur.Statement, "scoped to a named release") {
		t.Errorf("statement did not come from the bullet: %q", ur.Statement)
	}
	if strings.Contains(ur.Statement, "Blast radius") {
		t.Errorf("the statement ran on into the next bullet: %q", ur.Statement)
	}
}

// REQ-CROSS-075 (`RUN:2026-08-13`): a fifth declaration shape — the id leads
// the heading. One corpus writes its 89 modern epics as `## UR-ABS-1 — the user
// requirement` with the statement as the bold paragraph beneath. No "User
// outcome" heading exists, so every earlier shape misses and the epic yields no
// user requirement at all: 13 URs materialised for a tenant holding 4,051
// requirements, and every one of them an orphan.
func TestEpicUserRequirementFromIDLedHeading(t *testing.T) {
	record := `# EPIC-ABS-001 — Ask for time off

- **Context:** ABS (Absence & certificates)

## UR-ABS-1 — the user requirement

**As an employee who holds ` + "`Absence`" + `, I can record time I will not be working —
a whole period, one day, or part of one — see before I commit how many days it
will consume, and correct or withdraw it while it is still undecided.**

Cited, not assumed:

- The actor: the route admits exactly the holders of ` + "`Operation.Absence`" + `.
`
	ur, ok := ParseEpicUserRequirement(record)
	if !ok {
		t.Fatal("the id-led heading shape was not read at all")
	}
	if ur.ID != "UR-ABS-1" {
		t.Errorf("id = %q, want UR-ABS-1", ur.ID)
	}
	if !strings.Contains(ur.Statement, "record time I will not be working") {
		t.Errorf("statement did not come from the paragraph beneath: %q", ur.Statement)
	}
	if strings.Contains(ur.Statement, "Cited, not assumed") {
		t.Errorf("the statement ran on past its own paragraph: %q", ur.Statement)
	}
	if strings.Contains(ur.Statement, "**") {
		t.Errorf("bold markers reached the payload: %q", ur.Statement)
	}
}

// A heading that merely mentions a UR id in passing is not a declaration.
func TestEpicUserRequirementIgnoresAPassingHeadingMention(t *testing.T) {
	record := `# EPIC-X-001 — something

## How UR-NOPE-001 relates to this epic

Some prose about a different requirement.
`
	if ur, ok := ParseEpicUserRequirement(record); ok {
		t.Fatalf("a passing mention was read as a declaration: %+v", ur)
	}
}

// REQ-CROSS-099 — the two shapes a record actually writes an approval in. Both
// were read as unapproved: the table's first line is its header, not a decision,
// and the heading may name the approver rather than the act.
const tableApprovalRecord = `# EPIC-TST-082 — Table-shaped approval

## Human approval

| Approval id | Approver | Source | Decision |
|---|---|---|---|
| SPEC-APPROVE-EPIC-TST-082 | Pasi | ` + "`USER:2026-08-05`" + ` ("ok, approve them") | approved |
| APPROVE-EPIC-TST-082 | Pasi | ` + "`USER:2026-08-06`" + ` ("approve" after the summary) | approved |

## Done when
`

const tableApprovalPlainHeading = `# EPIC-TST-082b — Table under the plain heading

## Approval

| Approval id | Approver | Decision |
|---|---|---|
| APP-TST-082 | Pasi (` + "`USER:2026-07-21`" + `) | **APPROVED** — signed off. |

## Notes
`

func TestApprovalIsReadFromATableUnderHumanApproval(t *testing.T) {
	line := ApprovalLineOf(tableApprovalRecord)
	if line == "" {
		t.Fatal("a record whose approval is a table under '## Human approval' reads as unapproved")
	}
	if !strings.Contains(line, "USER:2026-08-06") {
		t.Fatalf("the approval line must carry the decision's own USER tag, got %q", line)
	}
}

func TestApprovalIsReadFromATableUnderThePlainHeading(t *testing.T) {
	line := ApprovalLineOf(tableApprovalPlainHeading)
	if line == "" {
		t.Fatal("a table under '## Approval' reads as unapproved because only its header row is inspected")
	}
	if !strings.Contains(line, "USER:2026-07-21") {
		t.Fatalf("wrong line returned: %q", line)
	}
}

// Guards — expected green from the start. These are what stop the widened
// reader from clearing the rule it exists to enforce.
func TestApprovalStaysEmptyWhenThereIsNone(t *testing.T) {
	if line := ApprovalLineOf(epicRecord); line != "" {
		t.Fatalf("_pending_ must still read as no approval, got %q", line)
	}
	if line := ApprovalLineOf("# EPIC-TST-082c — nothing\n\nJust prose.\n"); line != "" {
		t.Fatalf("a record with no approval section must read empty, got %q", line)
	}
}

// A table row with no USER tag anywhere is not an approval — and returning one
// would panic BuildEpicOp/BuildApprovalGateOp, which both slice tag[5:].
func TestApprovalRefusesATableRowWithNoUserTag(t *testing.T) {
	record := `# EPIC-TST-082d — unsourced

## Human approval

| Approval id | Approver | Decision |
|---|---|---|
| APP-TST-082 | Pasi | **APPROVED** — no date recorded. |
`
	if line := ApprovalLineOf(record); line != "" {
		t.Fatalf("an approval with no USER: source must not count, got %q", line)
	}
}

// The crash guard, stated as an invariant rather than as a case: every line
// this reader returns is sliced positionally at tag[5:] by two callers.
func TestEveryApprovalLineCarriesAUserTag(t *testing.T) {
	for i, record := range []string{
		tableApprovalRecord, tableApprovalPlainHeading, epicRecord, speccedRecord,
		"## Approval\nApproved by Pasi `USER:2026-08-06`.\n",
		"**APPROVED** — signed off `USER:2026-08-06`.\n",
	} {
		if line := ApprovalLineOf(record); line != "" && !userTagRe.MatchString(line) {
			t.Fatalf("case %d returned a tag-less line, which panics tag[5:]: %q", i, line)
		}
	}
}

// The approval basis is the justification a human gave, not the row's
// markup. CODE:epics/EPIC-PORTFOLIO-001-gallery-counts.md:153 — the record
// stores this exact row, and 11 more like it in the corpus stored the whole
// thing, verbatim pipes included, because the reader never looked past
// "starts with |". The Decision cell — the row's own header names it — is
// "approved"; nothing else in the row is the justification.
func TestApprovalBasisIsTheDecisionCellNotTheWholeRow(t *testing.T) {
	record := "# EPIC-PORTFOLIO-001 — Only\n\n## Human approval\n\n" +
		"| Approval id | Approver | Role | Source | Scope | Decision |\n|---|---|---|---|---|---|\n" +
		"| APP-PF-001 | Pasi | product owner | USER:2026-07-14:approve-portfolio-001-and-002 | EPIC-PORTFOLIO-001 | approved |\n"

	line := ApprovalLineOf(record)
	if line == "" {
		t.Fatal("a granted table row was dropped")
	}
	if strings.Contains(line, "product owner") || strings.Contains(line, "Pasi") {
		t.Fatalf("the whole row leaked instead of the Decision cell: %q", line)
	}
	if !strings.Contains(line, "approved") {
		t.Fatalf("the Decision cell's own text is missing: %q", line)
	}
	// The invariant every caller relies on: approvalTagOf(line) must still
	// find a tag, even though the Decision cell alone does not carry one.
	if got := ApprovalTagOf(line); got != "USER:2026-07-14" {
		t.Fatalf("the row's tag was lost when the row was trimmed to its Decision cell: %q from %q", got, line)
	}
}

// tableRowBasis reaches the epic op's stored basis, not just ApprovalLineOf's
// return value — this is what the store actually persisted as the whole row.
func TestEpicApprovalBasisIsTheDecisionCellInTheStore(t *testing.T) {
	record := "# EPIC-PORTFOLIO-001 — Only\n\n## Human approval\n\n" +
		"| Approval id | Approver | Role | Source | Scope | Decision |\n|---|---|---|---|---|---|\n" +
		"| APP-PF-001 | Pasi | product owner | USER:2026-07-14:approve-portfolio-001-and-002 | EPIC-PORTFOLIO-001 | approved |\n"
	op := BuildEpicOp(Epic{ID: "EPIC-PORTFOLIO-001"}, record)
	approval, ok := op.Payload["approval"].(map[string]any)
	if !ok {
		t.Fatal("a granted table row must still sync an approval")
	}
	basis, _ := approval["basis"].(string)
	if strings.HasPrefix(strings.TrimSpace(basis), "|") {
		t.Fatalf("the stored basis is the raw table row: %q", basis)
	}
}

// A join-the-wrapped-paragraph fix already exists for approvals scanned under
// a "## Approval"/"## Human approval"/"## Completion approval" heading
// (latestApprovalLine). CODE:epics/EPIC-AGT-901-agent-platform-as-built/EPIC.md:220-221
// records its approval under a "###" subsection instead, so it is read by
// approvalLineOf's fallback — which re-scans the whole document for a bare
// "**APPROVED" line — and that fallback must join a wrapped paragraph the
// same way, or it keeps only the first physical line.
func TestApprovedFallbackJoinsAWrappedParagraphOutsideAnyApprovalHeading(t *testing.T) {
	record := "# EPIC-AGT-901 — Only\n\n" +
		"### Not covered, for a third pass\n\n" +
		"`agents/x.ex`, `Core.Loader.Runtime`.\n\n" +
		"**APPROVED** — batch review recorded `USER:2026-08-13` (\"accept now all pending\n" +
		"ledger work regarding these, let's get them done!\").\n\n" +
		"What this approval covers, precisely: description only.\n"

	line := ApprovalLineOf(record)
	if line == "" {
		t.Fatal("the fallback dropped an approval that sits outside any '## Approval' heading")
	}
	if !strings.Contains(line, "accept now all pending") {
		t.Fatalf("approval = %q, want the human's quotation", line)
	}
	if !strings.Contains(line, "let's get them done") {
		t.Errorf("the fallback kept only the first physical line of the wrap\n  got: %q", line)
	}
	if strings.Contains(line, "description only") {
		t.Errorf("the fallback absorbed the following paragraph\n  got: %q", line)
	}
}

// The stored basis is text (unbounded, no contract limit — internal/opschema
// v1.json's approval.basis has no maxLength), so 300 is this builder's
// display choice, the same as decisionTitle's 200. It has to be honest about
// cutting: 9 of 157 stored approval bases sat at exactly 300 characters,
// mid-word, indistinguishable from a basis that simply ended there.
func TestALongApprovalBasisIsMarkedAsCut(t *testing.T) {
	long := "evidence reviewed and " + strings.Repeat("every loop verified again ", 12)
	record := "# EPIC-CV-040 — Only\n\n## Human approval\n\n" +
		"**APPROVED** — " + long + "`USER:2026-08-01`.\n"
	op := BuildEpicOp(Epic{ID: "EPIC-CV-040"}, record)
	approval := op.Payload["approval"].(map[string]any)
	basis, _ := approval["basis"].(string)

	if !strings.HasSuffix(basis, "…") {
		t.Errorf("a cut basis must show it was cut\n  got: %q", basis[max(0, len(basis)-60):])
	}
	if strings.HasSuffix(strings.TrimSuffix(basis, "…"), " ") {
		t.Errorf("cut at a word boundary, not mid-space: %q", basis)
	}
	if utf16Len(basis) > 300 {
		t.Errorf("basis is %d units, cap is 300", utf16Len(basis))
	}

	// A basis that fits is untouched — no ellipsis, no hash churn.
	short := "# EPIC-CV-041 — Only\n\n## Human approval\n\n**APPROVED** — reviewed `USER:2026-08-01`.\n"
	q := BuildEpicOp(Epic{ID: "EPIC-CV-041"}, short)
	qApproval := q.Payload["approval"].(map[string]any)
	if got, _ := qApproval["basis"].(string); got != "**APPROVED** — reviewed `USER:2026-08-01`." {
		t.Errorf("a short basis was altered: %q", got)
	}
}

// REQ-CROSS-110 — an approval answers a specific gate. Reading "an approval"
// without asking which one lets a specification approval stand in for a
// completion approval, marking an epic with nothing built as approved.
const specOnlyApprovalRecord = `# EPIC-TST-093 — Specified, not built

## Human approval

| Approval id | Approver | Source | Decision |
|---|---|---|---|
| SPEC-APPROVE-EPIC-TST-093 | Pasi | ` + "`USER:2026-08-13`" + ` ("specs approved, continue") | approved |

## Done when
`

const bothApprovalsRecord = `# EPIC-TST-093b — Specified and finished

## Human approval

| Approval id | Approver | Source | Decision |
|---|---|---|---|
| SPEC-APPROVE-EPIC-TST-093 | Pasi | ` + "`USER:2026-08-05`" + ` ("ok, approve them") | approved |
| APPROVE-EPIC-TST-093 | Pasi | ` + "`USER:2026-08-06`" + ` ("approve" after the summary) | approved |

## Done when
`

func TestASpecApprovalIsNotACompletionApproval(t *testing.T) {
	if line := ApprovalLineOf(specOnlyApprovalRecord); line != "" {
		t.Fatalf("a record whose ONLY approval is a specification approval must have no completion approval, got %q", line)
	}
}

// Guard, expected green from the start: where both exist the completion
// approval is still returned, which is what REQ-CROSS-099 established.
func TestBothApprovalsStillYieldTheCompletionOne(t *testing.T) {
	line := ApprovalLineOf(bothApprovalsRecord)
	if !strings.Contains(line, "USER:2026-08-06") || strings.Contains(line, "SPEC-APPROVE") {
		t.Fatalf("want the completion approval, got %q", line)
	}
}

// Guard: a prose-form specification approval must not stand in either.
func TestAProseSpecApprovalIsNotACompletionApproval(t *testing.T) {
	record := "# EPIC-TST-093c — x\n\n## Human approval\n\n" +
		"**Spec approval recorded:** `USER:2026-08-05` (SPEC-APPROVE-EPIC-TST-093, answered approve)\n"
	if line := ApprovalLineOf(record); line != "" {
		t.Fatalf("a prose specification approval is still not a completion approval, got %q", line)
	}
}

// ---------------------------------------------------------------------------
// REQ-CROSS-115 — an approval reader that reports the decision the record made.
//
// REQ-CROSS-099 widened this reader to see table rows, and REQ-CROSS-110 taught
// it which gate an approval answers. Neither taught it what the decision WAS, or
// which of a line's tags carries it. Every fixture below is a real record's
// shape, quoted from the corpus; measured against origin/main, each of the first
// four changed from "no approval" to "approved" when the reader was widened.
// ---------------------------------------------------------------------------

// CODE:epics/EPIC-FE-058-chat-first-nav-shell.md:54
const withheldPendingRecord = `# EPIC-TST-115a — pending, in the decision column

## Human approval
| Approval id | Approver | Decision |
|---|---|---|
| APP-TST-115a | (pending) | **pending — direct user correction (USER:2026-07-16); awaiting confirm** |
`

// CODE:epics/EPIC-PORTFOLIO-003-architecture-docs-facet.md:152
const withheldChangesRequestedRecord = `# EPIC-TST-115b — changes requested

## Human approval

| Approval id | Approver | Role | Source | Scope | Decision |
|---|---|---|---|---|---|
| APP-TST-115b | Pasi | product owner | USER:2026-07-14:only-ui-changes | EPIC-TST-115b | **changes requested** |
| APP-TST-115b2 | (pending) | product owner | - | EPIC-TST-115b (reworked) | pending re-review |
`

// CODE:epics/EPIC-EVAL-005-method-pilot-calibration-harness.md:97 — the decision
// cell grants the SPEC gate and defers the completion one to a later review.
const withheldFinalApprovalLaterRecord = `# EPIC-TST-115c — spec gate only, final approval later

## Human approval
| Approval id | Approver | Role | Source | Scope | Decision |
|---|---|---|---|---|---|
| APP-TST-115c | Ivan | method owner | ` + "`USER:2026-08-05`" + ` (plan approved, build entry) | EPIC-TST-115c | **spec gate approved**; final approval at pilot-report review (S7) |
`

// CODE:epics/EPIC-DEC-001-decision-experience/EPIC.md:97 — prose, and the line
// says in its first word that the gate it names is still open.
const withheldProseRecord = `# EPIC-TST-115d — awaiting the completion gate

## Approval

**Brief:**
- Recommendation: Approve — RED-first at every layer.

Pending — awaiting APPROVE-EPIC-TST-115d (SPEC-APPROVE approved ` + "`USER:2026-08-06`" + `).
`

func TestAWithheldDecisionIsNotAnApproval(t *testing.T) {
	for _, tc := range []struct {
		name   string
		record string
	}{
		{"pending in the decision column", withheldPendingRecord},
		{"changes requested", withheldChangesRequestedRecord},
		{"spec gate granted, final approval deferred", withheldFinalApprovalLaterRecord},
		{"prose saying the gate is still awaited", withheldProseRecord},
	} {
		if line := ApprovalLineOf(tc.record); line != "" {
			t.Errorf("%s: the record records no completion approval, got %q", tc.name, line)
		}
	}
}

// CODE:epics/EPIC-CHAT-002-spec-approval-and-auto-epic/EPIC.md:57 — one line,
// both gates. Skipping it whole drops a real, attributed completion approval;
// origin/main returned it and the epic is DONE.
const bothGatesOnOneLineRecord = `# EPIC-TST-115e — both gates, one line

## Approval
SPEC-APPROVE-EPIC-TST-115e: approved ` + "`USER:2026-08-06`" + `. APPROVE-EPIC-TST-115e: approved ` + "`USER:2026-08-06`" + ` ("approve" after the IN_REVIEW status walkthrough incl. the two recorded deferrals).
`

func TestALineNamingBothGatesStillYieldsTheCompletionApproval(t *testing.T) {
	line := ApprovalLineOf(bothGatesOnOneLineRecord)
	if line == "" {
		t.Fatal("a line recording both gates was discarded whole, losing a real completion approval")
	}
	if !strings.Contains(line, "APPROVE-EPIC-TST-115e: approved") {
		t.Fatalf("wrong line returned: %q", line)
	}
}

// The spec-approval rule must survive the **APPROVED fallback, which re-scans
// the whole document after latestApprovalLine has already rejected the line.
func TestTheApprovedFallbackDoesNotReadmitASpecApproval(t *testing.T) {
	record := "# EPIC-TST-115f — specified, not built\n\n## Human approval\n\n" +
		"**APPROVED** — specification approval recorded `USER:2026-08-05` (SPEC-APPROVE-EPIC-TST-115f); implementation may start.\n"
	if line := ApprovalLineOf(record); line != "" {
		t.Fatalf("the fallback readmitted the spec approval latestApprovalLine had rejected: %q", line)
	}
}

// CODE:epics/EPIC-EVAL-001-contracts-and-storage-substrate.md — one row, two
// tags: the build sanction and, a day later, the sign-off given after the
// evidence summary. The date rule exists so the first cannot stand for the
// second; inside one line it silently did.
func TestTheApprovalIsDatedByItsLatestTag(t *testing.T) {
	record := "# EPIC-TST-115g — two dates, one row\n\n## Human approval\n" +
		"| Approval id | Approver | Role | Source | Scope | Decision |\n|---|---|---|---|---|---|\n" +
		"| APP-TST-115g | Pasi | owner | `USER:2026-08-05` (build sanction) · `USER:2026-08-06` (\"approve\" — final sign-off after evidence summary) | EPIC-TST-115g | approved |\n"

	if got := ApprovalTagOf(ApprovalLineOf(record)); got != "USER:2026-08-06" {
		t.Fatalf("the sign-off is dated by the tag it was given with, want USER:2026-08-06, got %q", got)
	}
}

// Guards — expected green from the start. These are the shapes the corpus
// actually approves in; each is quoted from a record this change must not move.
func TestTheGrantedShapesInTheCorpusAreUnchanged(t *testing.T) {
	for _, tc := range []struct{ name, record, want string }{
		{"decision column reads approved",
			"## Human approval\n| Approval id | Approver | Role | Source | Scope | Decision |\n|---|---|---|---|---|---|\n| APP-TST-1 | Mattias | product owner | USER:2026-07-10:deemed-done | EPIC-TST-1 | approved |\n",
			"USER:2026-07-10"},
		{"approved with a trailing qualification",
			"## Human approval\n| Approval id | Approver | Source | Decision |\n|---|---|---|---|\n| APPROVE-EPIC-TST-2 | Pasi | `USER:2026-08-06` (\"approve\") | approved — deferrals routed as REQ-TST-039 |\n",
			"USER:2026-08-06"},
		{"APPROVED in the decision cell",
			"## Human approval\n| Approval id | Approver | Decision |\n|---|---|---|\n| APP-TST-3 | Pasi (`USER:2026-07-21`) | **APPROVED** — the reframed Map is what we want. |\n",
			"USER:2026-07-21"},
		{"prose beginning with the tag",
			"## Human approval\nUSER:2026-08-05 — Approved (gate APPROVE-EPIC-TST-4, answered via `factory answer`, option `approve`): release scoping.\n",
			"USER:2026-08-05"},
		{"prose beginning with a label",
			"## Human approval\n**Implementation approval recorded:** USER:2026-08-05 (gate APPROVE-EPIC-TST-5, answered via `factory answer`, option `approve`).\n",
			"USER:2026-08-05"},
		{"a batch approval that mentions pending work in its quoted words",
			"## Human approval\n**APPROVED** — batch review recorded `USER:2026-08-13` (\"accept now all pending requirements and epics\").\n",
			"USER:2026-08-13"},
		{"conditional approval, condition since met",
			"## Human approval\n| Approval id | Approver | Source | Decision |\n|---|---|---|---|\n| APPROVE-EPIC-TST-7 | Pasi | `USER:2026-08-06` (approval conditional on a real-key assist test; it passed live, then \"Approve\") | approved |\n",
			"USER:2026-08-06"},
	} {
		line := ApprovalLineOf(tc.record)
		if line == "" {
			t.Errorf("%s: a granted approval was dropped", tc.name)
			continue
		}
		if got := ApprovalTagOf(line); got != tc.want {
			t.Errorf("%s: want %s, got %q from %q", tc.name, tc.want, got, line)
		}
	}
}

// A tagged line that records no decision at all is not an approval. The Brief
// block a gate carries quotes the request's own USER: tag, and the section scan
// walks every line — so "not withheld" cannot be the whole test, or the brief
// bullet stands in for the decision the section is still waiting on.
const neutralTaggedProseRecord = `# EPIC-TST-120a — briefed, undecided

## Approval

**Brief:**
- What: ship the estate map (requested ` + "`USER:2026-08-10`" + `)
- Risk if wrong: reversible.

Awaiting the completion gate.
`

func TestANeutralTaggedProseLineIsNotAnApproval(t *testing.T) {
	if line := ApprovalLineOf(neutralTaggedProseRecord); line != "" {
		t.Fatalf("a brief bullet records no decision, got %q", line)
	}
	if line := CompletionApprovalIn("see record (`USER:2026-08-10`)"); line != "" {
		t.Fatalf("a work-list pointer cell records no decision, got %q", line)
	}
}

// The template's approval tables end in a Conditions column, and conditions are
// routinely written as "pending X" — a note about remaining work, not the
// decision. The decision is the first cell that reads as one; a later cell
// cannot withdraw what the decision column granted.
const grantedWithPendingConditionsRecord = `# EPIC-TST-120b — approved, conditions noted

## Completion approval

| Gate | Approver | Role | Source | Decision | Conditions |
|---|---|---|---|---|---|
| APPROVE-EPIC-TST-120b | Pasi | owner | ` + "`USER:2026-08-14`" + ` | approved | pending deferrals: REQ-TST-039 |
`

func TestAConditionsCellDoesNotVetoAGrantedDecision(t *testing.T) {
	line := ApprovalLineOf(grantedWithPendingConditionsRecord)
	if line == "" {
		t.Fatal("a granted decision was vetoed by its own conditions cell")
	}
	if got := ApprovalTagOf(line); got != "USER:2026-08-14" {
		t.Fatalf("wrong line returned: %q", line)
	}
}

// Guard, expected green from the start: when the decision column itself
// withholds, no other cell rescues the row.
func TestAWithheldDecisionCellStillVetoesTheRow(t *testing.T) {
	record := "## Completion approval\n| Gate | Approver | Decision | Conditions |\n|---|---|---|---|\n" +
		"| APPROVE-EPIC-TST-120c | Pasi | changes requested `USER:2026-08-14` | Approve after rework |\n"
	if line := ApprovalLineOf(record); line != "" {
		t.Fatalf("a withheld decision column must settle the row, got %q", line)
	}
}

// The decision is the cell the HEADER designates, not the first cell that
// happens to read as one: a Role cell saying "sign-off authority" describes
// who may decide, while the Decision cell's "pending" is the decision.
func TestARoleCellCannotGrantWhatTheDecisionColumnWithholds(t *testing.T) {
	record := "## Completion approval\n" +
		"| Gate | Approver | Role | Source | Decision |\n|---|---|---|---|---|\n" +
		"| APPROVE-EPIC-TST-130 | Pasi | sign-off authority | `USER:2026-08-14` | pending |\n"
	if line := ApprovalLineOf(record); line != "" {
		t.Fatalf("the Role cell granted what the Decision column withholds, got %q", line)
	}
}

// A table whose header designates no Decision column records no readable
// decision. Conservative and visible in sync, like an unknown heading prefix:
// guessing which cell decides is how the Role cell above became an approval.
func TestATableWithoutADecisionColumnRecordsNoDecision(t *testing.T) {
	record := "## Completion approval\n" +
		"| Gate | Approver | Notes |\n|---|---|---|\n" +
		"| APPROVE-EPIC-TST-131 | Pasi | approved `USER:2026-08-14` |\n"
	if line := ApprovalLineOf(record); line != "" {
		t.Fatalf("a table with no Decision column must record no decision, got %q", line)
	}
}

// A cell may contain an escaped pipe — splitCells exists for exactly this —
// and splitting on every "|" shifts the cells after it, so a word from a
// Source cell lands in the header's Decision index while the real Decision
// cell says pending. The reader must split the way the rest of the parser does.
func TestAnEscapedPipeCannotShiftAWordIntoTheDecisionColumn(t *testing.T) {
	record := "## Completion approval\n" +
		"| Gate | Source | Decision |\n|---|---|---|\n" +
		"| APPROVE-EPIC-TST-140 | `USER:2026-08-14` said \\| approved earlier | pending |\n"
	if line := ApprovalLineOf(record); line != "" {
		t.Fatalf("an escaped pipe shifted a Source word into the Decision column: %q", line)
	}
}

// The same shift also loses real approvals: with the cells moved over, the
// Decision index reads a fragment of the Notes cell instead of the granted
// one. An escaped pipe is cell content; only unescaped pipes delimit.
func TestAnEscapedPipeDoesNotCostAGrantedRowItsApproval(t *testing.T) {
	record := "## Completion approval\n" +
		"| Gate | Notes | Decision |\n|---|---|---|\n" +
		"| APPROVE-EPIC-TST-141 | reduces \\|drift\\| toward zero | approved `USER:2026-08-14` |\n"
	line := ApprovalLineOf(record)
	if line == "" {
		t.Fatal("an escaped pipe in a Notes cell cost the granted row its approval")
	}
	if got := ApprovalTagOf(line); got != "USER:2026-08-14" {
		t.Fatalf("wrong line returned: %q", line)
	}
}

// A standing _pending_ marker vetoes its whole section, even when a dated
// granted row sits below it. Deliberate: failing toward "no approval" is the
// safe direction for an approval reader, and the record this could hurt — a
// migration leaving its old stub behind — keeps that stub in a SEPARATE
// section, which the cross-section scan already handles.
func TestAPendingMarkerVetoesItsWholeSection(t *testing.T) {
	record := "## Completion approval\n\n_Pending — final sign-off at the pilot review._\n\n" +
		"| Gate | Approver | Decision |\n|---|---|---|\n" +
		"| APPROVE-EPIC-TST-142 | Pasi | approved `USER:2026-08-14` |\n"
	if line := ApprovalLineOf(record); line != "" {
		t.Fatalf("a dated row outranked its section's standing _pending_ marker: %q", line)
	}
}

// APPROVE inside the gate's own id is the gate's name, not its answer. A prose
// line that only NAMES the gate records no decision.
func TestAGateIdInProseIsNotAGrant(t *testing.T) {
	record := "## Completion approval\n" +
		"Gate APPROVE-EPIC-TST-132 requested by USER:2026-08-14 — response recorded in thread.\n"
	if line := ApprovalLineOf(record); line != "" {
		t.Fatalf("the gate's own id was read as its decision, got %q", line)
	}
}

// A negative decision is a decision wherever it sits on the line — "not
// approved" mid-prose must veto even though the line does not open with it,
// and the grant vocabulary inside it ("approved") must not rescue the line.
func TestANegativeDecisionMidProseVetoes(t *testing.T) {
	for _, line := range []string{
		"Reviewed by Pasi `USER:2026-08-14` — not approved; rework the sync path first.",
		"Gate APPROVE-EPIC-TST-133 requested by USER:2026-08-14; no decision yet.",
	} {
		if got := ApprovalLineOf("## Completion approval\n" + line + "\n"); got != "" {
			t.Errorf("a negative decision mid-line was read as a grant: %q", got)
		}
	}
}

// A record migrating toward the installed template keeps its old `## Approval`
// stub — often still saying _pending_ — above the template's
// `## Completion approval` table. The reader scans every approval section, not
// the first heading it happens to find, so the stub cannot shadow the grant.
const pendingStubBeforeGrantedTableRecord = `# EPIC-TST-120d — migrated record

## Approval

_pending._

## Completion approval

| Gate | Approver | Role | Source | Decision | Conditions |
|---|---|---|---|---|---|
| APPROVE-EPIC-TST-120d | Pasi | owner | ` + "`USER:2026-08-14`" + ` | approved | none |
`

func TestAPendingStubDoesNotShadowAGrantedCompletionSection(t *testing.T) {
	line := ApprovalLineOf(pendingStubBeforeGrantedTableRecord)
	if line == "" {
		t.Fatal("the pending stub shadowed the granted completion table")
	}
	if got := ApprovalTagOf(line); got != "USER:2026-08-14" {
		t.Fatalf("wrong line returned: %q", line)
	}
}

// ---------------------------------------------------------------------------
// REQ-CROSS-114 — an epic written from the template the CLI installs is read by
// the extractor the CLI ships.
//
// The template arrived from the req-driven-dev subtree naming three sections
// this reader had never heard of: `## Journeys and acceptance scenarios`,
// `## Specification approval` and `## Completion approval`. Every record then in
// the corpus used the older headings, so nothing failed — the first epic
// written from the template synced with no scenarios and neither approval.
// ---------------------------------------------------------------------------

// The shape `.modernpath/rdd/templates/work/EPIC.md` prescribes, filled in as a
// finished epic. The pin in internal/kit runs the same assertions against the
// installed template itself; this fixture keeps the reader's own tests readable.
const templateShapedRecord = `# EPIC-TST-114 — Written from the template

- **Release/system:** modernpath-v1-09

## Specification status

SPEC-APPROVED — approved by Mattias, workspace owner, in chat
` + "`USER:2026-08-13:SPEC-APPROVE-EPIC-TST-114`" + ` ("Ok, specs approved.").

## Journeys and acceptance scenarios

| SCN | UR/journey | Given/When/Then | Upper RED | Passing evidence | Code | Status |
|---|---|---|---|---|---|---|
| SCN-TST-001 | UR-TST-001 | GIVEN an epic written from the template WHEN sync runs THEN its scenarios reach the platform | — | — | — | UPPER_VALIDATED |

## Specification approval

| Gate | Approver | Role | Source | Decision | Conditions |
|---|---|---|---|---|---|
| SPEC-APPROVE-EPIC-TST-114 | Mattias | workspace owner | ` + "`USER:2026-08-13:SPEC-APPROVE-EPIC-TST-114`" + ` | approved | D-1..4 approved; continue. |

## Completion approval

| Gate | Approver | Role | Source | Decision | Conditions |
|---|---|---|---|---|---|
| APPROVE-EPIC-TST-114 | Mattias | workspace owner | ` + "`USER:2026-08-14:APPROVE-EPIC-TST-114`" + ` | approved | Evidence reviewed. |

## Completion record

- **Done:** the slice.
`

func TestTemplateScenariosReachThePlatform(t *testing.T) {
	got := ParseScenarios(templateShapedRecord, "EPIC-TST-114")
	if len(got) != 1 {
		t.Fatalf("the template's scenario heading is unread: got %d scenarios, want 1", len(got))
	}
	if id := got[0].(map[string]any)["external_id"]; id != "EPIC-TST-114#SCN-TST-001" {
		t.Errorf("external_id = %v, want EPIC-TST-114#SCN-TST-001", id)
	}
}

func TestTemplateCompletionApprovalIsRead(t *testing.T) {
	line := ApprovalLineOf(templateShapedRecord)
	if line == "" {
		t.Fatal("the template's '## Completion approval' table reads as no approval")
	}
	if got := ApprovalTagOf(line); got != "USER:2026-08-14" {
		t.Fatalf("want the completion approval's own tag USER:2026-08-14, got %q from %q", got, line)
	}
}

func TestTemplateSpecificationApprovalIsRead(t *testing.T) {
	marker, line := SpecApprovalLineOf(templateShapedRecord)
	if marker != "approved" {
		t.Fatalf("marker = %q, want approved — the record's own '## Specification approval' table grants it (line %q)", marker, line)
	}
	if !strings.Contains(line, "USER:2026-08-13") {
		t.Errorf("the returned line must carry the approval's source, got %q", line)
	}
}

// Guard: the two approval sections answer different gates, and widening the
// completion reader must not let the specification one stand in for it — the
// exact substitution REQ-CROSS-110 was raised to stop.
func TestTheSpecificationApprovalSectionIsNotACompletionApproval(t *testing.T) {
	record := `# EPIC-TST-114b — specified, not finished

## Specification approval

| Gate | Approver | Role | Source | Decision | Conditions |
|---|---|---|---|---|---|
| SPEC-APPROVE-EPIC-TST-114b | Mattias | workspace owner | ` + "`USER:2026-08-13`" + ` | approved | continue. |

## Completion approval

| Gate | Approver | Role | Source | Decision | Conditions |
|---|---|---|---|---|---|
| APPROVE-EPIC-TST-114b | — | — | — | pending | — |
`
	if line := ApprovalLineOf(record); line != "" {
		t.Fatalf("a granted SPEC approval over a pending completion row must not read as completion-approved, got %q", line)
	}
}

// Guard: the template ships both tables pre-filled with a placeholder row. An
// unanswered gate must stay unanswered — the placeholder is the shape every new
// epic starts in, so reading it as a decision would manufacture approvals
// wholesale.
func TestTheUnfilledTemplateGrantsNothing(t *testing.T) {
	unfilled := `# EPIC-«AREA»-«NNN» — «Capability»

## Specification status

SPEC-DRAFT — «scope of the specs set»

## Journeys and acceptance scenarios

| SCN | UR/journey | Given/When/Then | Upper RED | Passing evidence | Code | Status |
|---|---|---|---|---|---|---|
| SCN-«AREA»-«NNN» | UR-«AREA»-«NNN» | «G/W/T or link» | — | — | — | PROPOSED |

## Specification approval

| Gate | Approver | Role | Source | Decision | Conditions |
|---|---|---|---|---|---|
| SPEC-APPROVE-EPIC-«AREA»-«NNN» | — | — | — | pending | — |

## Completion approval

| Gate | Approver | Role | Source | Decision | Conditions |
|---|---|---|---|---|---|
| APPROVE-EPIC-«AREA»-«NNN» | — | — | — | pending | — |
`
	if line := ApprovalLineOf(unfilled); line != "" {
		t.Errorf("the template's pending completion row must not be an approval, got %q", line)
	}
	if marker, line := SpecApprovalLineOf(unfilled); marker != "draft" {
		t.Errorf("marker = %q (line %q), want draft", marker, line)
	}
	if got := ParseScenarios(unfilled, "EPIC-TST-114c"); len(got) != 0 {
		t.Errorf("the placeholder scenario row carries no SCN id and must yield nothing, got %d", len(got))
	}
}

// A record that says SPEC-DRAFT while its approval table says approved
// contradicts itself. The published reading is the conservative one; the
// contradiction is warned about at snapshot time rather than resolved silently
// (the precedent is collectEpicSpecs' "an approval over nothing is dishonest").
func TestADraftMarkerIsNotLiftedByAnApprovalTable(t *testing.T) {
	record := `# EPIC-TST-114d — still drafting

## Specification status

SPEC-DRAFT — the specs set is still being written

## Specification approval

| Gate | Approver | Role | Source | Decision | Conditions |
|---|---|---|---|---|---|
| SPEC-APPROVE-EPIC-TST-114d | Mattias | workspace owner | ` + "`USER:2026-08-13`" + ` | approved | — |
`
	if marker, line := SpecApprovalLineOf(record); marker != "draft" {
		t.Fatalf("marker = %q (line %q), want draft — a record that calls itself a draft is not approved", marker, line)
	}
}

// Guard: a completion approval written under the specification heading is not a
// specification approval — the mirror of the veto isCompletionApproval applies.
func TestACompletionRowUnderTheSpecificationHeadingIsNotASpecApproval(t *testing.T) {
	record := `# EPIC-TST-114e — x

## Specification status

SPEC-READY — the specs set is complete

## Specification approval

| Gate | Approver | Role | Source | Decision | Conditions |
|---|---|---|---|---|---|
| APPROVE-EPIC-TST-114e | Mattias | workspace owner | ` + "`USER:2026-08-13`" + ` | approved | — |
`
	if marker, line := SpecApprovalLineOf(record); marker != "ready" {
		t.Fatalf("marker = %q (line %q), want ready — the row answers the completion gate", marker, line)
	}
}

// Guards on the corpus shapes this widening must not move: the older scenario
// headings, and a specification marker that carries its own tag.
func TestTheCorpusShapesStillParseAsBefore(t *testing.T) {
	for _, heading := range []string{
		"## BDD acceptance scenarios",
		"## Acceptance scenarios",
		"## BDD acceptance scenarios (SCN — upper loop)",
	} {
		record := "# EPIC-TST-114f — x\n\n" + heading + "\n" +
			"| SCN | Summary | Status |\n|---|---|---|\n" +
			"| SCN-TST-009 | A scenario. | DONE |\n\n## Next\n"
		if got := ParseScenarios(record, "EPIC-TST-114f"); len(got) != 1 {
			t.Errorf("%q: got %d scenarios, want 1", heading, len(got))
		}
	}

	tagged := "# EPIC-TST-114g — x\n\n## Specification status\n\nSPEC-APPROVED — `USER:2026-08-09` batch approval.\n"
	if marker, _ := SpecApprovalLineOf(tagged); marker != "approved" {
		t.Errorf("a marker carrying its own tag must still read approved, got %q", marker)
	}
	ready := "# EPIC-TST-114h — x\n\n## Specification status\n\nSPEC-READY — specs complete.\n"
	if marker, _ := SpecApprovalLineOf(ready); marker != "ready" {
		t.Errorf("SPEC-READY with no approval anywhere must stay ready, got %q", marker)
	}
	derived := "# EPIC-TST-114i — x\n\n## Specification status\n\nSPEC-DERIVED — reverse-engineered from shipped code.\n"
	if marker, _ := SpecApprovalLineOf(derived); marker != "" {
		t.Errorf("an as-built record must stay unmarked, got %q", marker)
	}
}

// A `## Linked user requirements` table declares one membership per data row.
// Reading only the first row keeps the epic's first user requirement and
// silently loses every one beneath it: the entity may still exist because
// another record defines it, but this epic's membership edge to it is never
// written and the join reads as complete.
//
// The record here also carries the three tables that sit next to a real
// linked-user-requirements section — requirement traceability, source material,
// and a cross-reference heading — none of which declare membership. Widening
// the reader must not sweep them in.
const twoLinkedURsRecord = `# EPIC-TWO-001 - Two linked user requirements

## User outcome

The epic delivers two distinct outcomes, and says so in its table.

## Linked user requirements

| User requirement | Statement | Status |
|---|---|---|
| UR-TWO-001 | The system shall do the first thing the epic delivers. | VALIDATED |
| UR-TWO-002 | The system shall do the second thing the epic delivers. | IN_PROGRESS |

## Requirement traceability

| User requirement | Acceptance scenario | System requirement | Why the SR exists | Status |
|---|---|---|---|---|
| UR-TWO-001 | SCN-TWO-001 | SR-TWO-001 | because | LOWER_VERIFIED |
| UR-NOPE-003 | SCN-TWO-002 | SR-TWO-002 | because | LOWER_VERIFIED |

## Source material

| Source id | Type | Reference | Notes |
|---|---|---|---|
| UR-NOPE-004 | doc | somewhere.md | not a declaration |

## How UR-NOPE-005 relates to this epic

Prose about a requirement this epic does not carry.
`

func urIDsOf(urs []UserRequirement) []string {
	out := make([]string, 0, len(urs))
	for _, ur := range urs {
		out = append(out, ur.ID)
	}
	return out
}

func TestEpicUserRequirementsReadEveryLinkedTableRow(t *testing.T) {
	urs := ParseEpicUserRequirements(twoLinkedURsRecord)
	if got := urIDsOf(urs); len(got) != 2 || got[0] != "UR-TWO-001" || got[1] != "UR-TWO-002" {
		t.Fatalf("declared user requirements = %v, want [UR-TWO-001 UR-TWO-002] in declaration order", got)
	}
	if !strings.Contains(urs[1].Statement, "second thing") {
		t.Errorf("the second row's statement did not come from its own row: %q", urs[1].Statement)
	}
	// The singular reader is unchanged: the first declaration still leads.
	first, ok := ParseEpicUserRequirement(twoLinkedURsRecord)
	if !ok || first.ID != urs[0].ID {
		t.Errorf("the single-UR reader changed: %q/%v, want %q", first.ID, ok, urs[0].ID)
	}
}

// Negative pin for the widening: only the linked-user-requirements section
// declares membership. A traceability table, a source-material table and a
// cross-reference heading all name UR ids without declaring one.
func TestEpicUserRequirementsIgnoreNonMembershipTables(t *testing.T) {
	for _, ur := range ParseEpicUserRequirements(twoLinkedURsRecord) {
		if strings.HasPrefix(ur.ID, "UR-NOPE-") {
			t.Fatalf("a UR was mined out of a non-membership shape: %+v", ur)
		}
	}
	// A record with no linked-user-requirements section at all declares nothing,
	// however many UR ids its other tables mention.
	traceOnly := `# EPIC-TRACE-001 - traceability only

## Requirement traceability

| User requirement | System requirement | Status |
|---|---|---|
| UR-NOPE-001 | SR-TRACE-001 | LOWER_VERIFIED |
| UR-NOPE-002 | SR-TRACE-002 | LOWER_VERIFIED |
`
	if urs := ParseEpicUserRequirements(traceOnly); len(urs) != 0 {
		t.Fatalf("traceability rows became declarations: %v", urIDsOf(urs))
	}
}

// The declared heading still leads the list where both shapes are present, and
// the table's other rows are memberships beside it rather than replacements.
func TestEpicUserRequirementsKeepTheHeadingFirst(t *testing.T) {
	record := `# EPIC-SY-010 — epics carry their state

## User outcome (UR-SY-010)
An epic's real state and its acceptance scenarios are visible in the app.

## Linked user requirements
| UR | Statement | Status |
|---|---|---|
| UR-OTHER-999 | Something else entirely. | TODO |
`
	got := urIDsOf(ParseEpicUserRequirements(record))
	if len(got) != 2 || got[0] != "UR-SY-010" || got[1] != "UR-OTHER-999" {
		t.Fatalf("declared user requirements = %v, want [UR-SY-010 UR-OTHER-999]", got)
	}
}

func TestEpicOpCarriesEveryDeclaredUserRequirement(t *testing.T) {
	epic := Epic{ID: "EPIC-TWO-001", State: "in-progress"}
	op := BuildEpicOp(epic, twoLinkedURsRecord)
	ids, _ := op.Payload["user_requirement_external_ids"].([]string)
	if len(ids) != 2 || ids[0] != "UR-TWO-001" || ids[1] != "UR-TWO-002" {
		t.Fatalf("user_requirement_external_ids = %v, want both declared memberships", op.Payload["user_requirement_external_ids"])
	}
}

// One user-requirement op per declared UR — an id that reaches no op has no
// entity for the membership edge to point at. The ledger-derived row still
// wins over the epic-derived one for an id declared in both places.
func TestBuildOpsEmitsAnOpPerDeclaredUserRequirement(t *testing.T) {
	data := Data{
		Epics: []Epic{{ID: "EPIC-TWO-001", Record: "epics/EPIC-TWO-001.md", State: "in-progress"}},
	}
	ops := BuildOps(data, func(string) string { return twoLinkedURsRecord }, "2026-08-22")

	urOps := map[string]map[string]any{}
	for _, op := range ops {
		if op.Type != "upsert_requirement" || op.Payload["kind"] != "user" {
			continue
		}
		id, _ := op.Payload["external_id"].(string)
		urOps[id] = op.Payload
	}
	if len(urOps) != 2 {
		t.Fatalf("user-requirement ops = %d (%v), want one per declared UR", len(urOps), urOps)
	}
	second := urOps["UR-TWO-002"]
	if second == nil {
		t.Fatal("the second declared user requirement reached no op")
	}
	if desc, _ := second["description"].(string); !strings.Contains(desc, "second thing") {
		t.Errorf("the second UR's description is not its own row's statement: %q", desc)
	}
	if title, _ := second["title"].(string); title == "" {
		t.Error("the second UR reached an op with no title")
	}
	if cits, _ := second["source_citations"].([]any); len(cits) == 0 {
		t.Error("the second UR carries no epic citation")
	}
}

func TestLedgerUserRequirementStillWinsOverASecondEpicDeclaration(t *testing.T) {
	data := Data{
		UserReqs: []FileUR{{ID: "UR-TWO-002", Title: "Two", Statement: "The ledger's own richer statement.", Status: "TODO"}},
		Epics:    []Epic{{ID: "EPIC-TWO-001", Record: "epics/EPIC-TWO-001.md", State: "in-progress"}},
	}
	ops := BuildOps(data, func(string) string { return twoLinkedURsRecord }, "2026-08-22")
	seen := 0
	for _, op := range ops {
		if op.Type != "upsert_requirement" || op.Payload["kind"] != "user" {
			continue
		}
		if op.Payload["external_id"] != "UR-TWO-002" {
			continue
		}
		seen++
		if desc, _ := op.Payload["description"].(string); !strings.Contains(desc, "ledger's own richer statement") {
			t.Errorf("the epic-derived row overwrote the file-derived one: %q", desc)
		}
	}
	if seen != 1 {
		t.Fatalf("UR-TWO-002 emitted %d ops, want exactly one", seen)
	}
}

// The single-UR reader takes the FIRST id-led heading and nothing else: a
// leading heading whose body states nothing yields nothing, rather than
// reaching past it to a later heading. Walking every heading is the plural
// reader's job, and the two must not be collapsed into one — the mirror in
// ops.js has to make the same distinction or the builders drift.
func TestSingleReaderStopsAtTheFirstIDLedHeading(t *testing.T) {
	record := `# EPIC-LED-001 — two id-led headings

## UR-LED-001 — the first outcome

## UR-LED-002 — the second outcome

As an operator I want the second outcome so that it is delivered.
`
	if ur, ok := ParseEpicUserRequirement(record); ok {
		t.Fatalf("the statement-less leading heading was skipped: %+v", ur)
	}
	got := urIDsOf(ParseEpicUserRequirements(record))
	if len(got) != 1 || got[0] != "UR-LED-002" {
		t.Fatalf("declared user requirements = %v, want only the heading that states one", got)
	}
}

// Three consecutive id-led headings, each stating its outcome. A reader that
// scans one pattern over the whole record consumes the `\n##` that ends each
// body, so its next scan starts inside the following heading line and misses
// it: three headings read as the first and the third. Walking the headings by
// index is what keeps the middle one, and only a record with three of them can
// tell the two readings apart — with two, the swallowed one is the last, and a
// reader that loses the last looks the same as one that stops early.
const threeIDLedOutcomesRecord = `# EPIC-LED-001 — three id-led headings

## UR-LED-001 — the first outcome

As a reader I want the first outcome so that it is delivered.

## UR-LED-002 — the second outcome

As an operator I want the second outcome so that it is delivered.

## UR-LED-003 — the third outcome

As an auditor I want the third outcome so that it is delivered.
`

func TestEveryIDLedHeadingIsReadNotEverySecondOne(t *testing.T) {
	got := urIDsOf(parseIDLedOutcomes(threeIDLedOutcomesRecord))
	want := []string{"UR-LED-001", "UR-LED-002", "UR-LED-003"}
	if len(got) != len(want) {
		t.Fatalf("id-led outcomes = %v, want %v", got, want)
	}
	for i, id := range want {
		if got[i] != id {
			t.Fatalf("id-led outcomes = %v, want %v", got, want)
		}
	}
	// Each statement comes from its own heading's body, not a neighbour's.
	for _, ur := range parseIDLedOutcomes(threeIDLedOutcomesRecord) {
		switch ur.ID {
		case "UR-LED-001":
			if !strings.Contains(ur.Statement, "first outcome") {
				t.Errorf("%s took a neighbour's body: %q", ur.ID, ur.Statement)
			}
		case "UR-LED-002":
			if !strings.Contains(ur.Statement, "second outcome") {
				t.Errorf("%s took a neighbour's body: %q", ur.ID, ur.Statement)
			}
		case "UR-LED-003":
			if !strings.Contains(ur.Statement, "third outcome") {
				t.Errorf("%s took a neighbour's body: %q", ur.ID, ur.Statement)
			}
		}
	}
	if ids := urIDsOf(ParseEpicUserRequirements(threeIDLedOutcomesRecord)); len(ids) != 3 {
		t.Fatalf("declared user requirements = %v, want all three", ids)
	}
	// The singular reader still answers its own question: the leading one.
	if ur, ok := ParseEpicUserRequirement(threeIDLedOutcomesRecord); !ok || ur.ID != "UR-LED-001" {
		t.Fatalf("single-UR reader = %q/%v, want UR-LED-001", ur.ID, ok)
	}
}

// A row that names a user requirement and states nothing about it is not a
// declaration the builder can carry: an entity built from it would need its
// statement invented, and an invented user requirement is indistinguishable
// from a real one. Both the shape readers and the collector enforce this, so
// the pin has to name the outcome rather than either guard.
func TestADeclarationNeedsBothAnIDAndAStatement(t *testing.T) {
	record := `# EPIC-BLANK-001 - a stated row and a blank one

## Linked user requirements

| User requirement | Statement | Status |
|---|---|---|
| UR-BLANK-001 | The system shall do the thing that is stated. | VALIDATED |
| UR-BLANK-002 |  | IN_PROGRESS |
`
	got := urIDsOf(ParseEpicUserRequirements(record))
	if len(got) != 1 || got[0] != "UR-BLANK-001" {
		t.Fatalf("declared user requirements = %v, want only the stated row", got)
	}

	// …and nothing downstream invents one either: no membership edge and no
	// entity for the blank row.
	op := BuildEpicOp(Epic{ID: "EPIC-BLANK-001", State: "in-progress"}, record)
	ids, _ := op.Payload["user_requirement_external_ids"].([]string)
	if len(ids) != 1 || ids[0] != "UR-BLANK-001" {
		t.Fatalf("user_requirement_external_ids = %v, want only the stated row", op.Payload["user_requirement_external_ids"])
	}
	ops := BuildOps(Data{Epics: []Epic{{ID: "EPIC-BLANK-001", Record: "epics/EPIC-BLANK-001.md", State: "in-progress"}}},
		func(string) string { return record }, "2026-08-22")
	for _, o := range ops {
		if o.Type == "upsert_requirement" && o.Payload["kind"] == "user" && o.Payload["external_id"] == "UR-BLANK-002" {
			t.Fatalf("the blank row reached a user-requirement op: %v", o.Payload)
		}
	}
}

// REQ-PLN-054: "the user outcome is what an epic IS about; without it the app
// can only show an id and a title." ParseEpicDescription read exactly one
// shape — a `## User outcome` heading — so 34 of 190 epic records landed with
// no description at all, while 186 of the 190 fit the heading rule.
//
// The fallbacks are ordered by how much they assume, and both are grounded in
// what the corpus was measured to contain:
//
//  1. The user-requirement statement the EXISTING parsers already extract.
//     Nine of the 34 declare their outcome as a labelled bullet —
//     `- **User outcome (UR-SYNC-001):** …`, `- **UR:** …` — which
//     ParseEpicUserRequirement reads today. Reusing it invents nothing: it is
//     the same sentence, from a parser that already recognizes the shape.
//
//  2. Failing that, the record's opening paragraph — but only when it is
//     prose. Twenty-six records open with a real description ("A real UX fix:
//     the Knowledge Core Capabilities table renders every capability…"), and
//     the rest open with a metadata banner (`- **Status:** IN_PROGRESS ·
//     **Owner:** …`). A list is never a description, so a leading list marker
//     disqualifies the paragraph rather than filling the field with metadata.
//
// The heading path is untouched, so no epic that has a description today gets
// a different one — and no content hash moves for them.
func TestEpicDescriptionFallsBackToWhatTheRecordDeclares(t *testing.T) {
	// 1. The heading still wins, unchanged.
	heading := "# EPIC-CV-001 — Only\n\n## User outcome\nThe portfolio renders real systems.\n"
	if got := ParseEpicDescription(heading); got != "The portfolio renders real systems." {
		t.Errorf("heading path changed: %q", got)
	}

	// 2. A labelled outcome bullet, the shape nine records use.
	bullet := "# EPIC-SYNC-001 — Sync\n\n" +
		"- **Status:** IN_REVIEW (evidence-complete)\n" +
		"- **User outcome (UR-SYNC-001):** As the team, we see our requirements inside ModernPath itself.\n\n" +
		"## Scenarios\n"
	got := ParseEpicDescription(bullet)
	if !strings.Contains(got, "we see our requirements inside ModernPath") {
		t.Errorf("description = %q, want the outcome the bullet declares", got)
	}
	if strings.Contains(got, "IN_REVIEW") {
		t.Errorf("description = %q, must not be the status banner", got)
	}

	// 3. An opening prose paragraph is a description.
	prose := "# EPIC-FE-022 — Capabilities filter\n\n" +
		"A real UX fix: the Knowledge Core Capabilities table renders every capability a system\n" +
		"has with no way to narrow it.\n\n## Tasks\n"
	got = ParseEpicDescription(prose)
	if !strings.Contains(got, "A real UX fix") {
		t.Errorf("description = %q, want the opening paragraph", got)
	}
	// Hard-wrapped prose is one sentence, not one line.
	if !strings.Contains(got, "no way to narrow it") {
		t.Errorf("description = %q, want the whole wrapped paragraph", got)
	}

	// 4. A bolded lead is prose, not a list.
	bold := "# EPIC-FE-037 — Downgrade fix\n\n" +
		"**A defect found in an honest self-review of the branch.** The inline editor\n" +
		"could not downgrade a full-access key.\n\n## Tasks\n"
	if got = ParseEpicDescription(bold); !strings.Contains(got, "honest self-review") {
		t.Errorf("description = %q, want the bolded prose lead", got)
	}

	// 5. A metadata banner is not a description — better empty than wrong.
	meta := "# EPIC-AUTH-001 — Login\n\n" +
		"- **Status:** IN_PROGRESS · **Owner:** Pasi (approval) · **Started:** 2026-08-06\n" +
		"- **Ledger:** `REQ-PLT-016`\n\n## Tasks\n"
	if got = ParseEpicDescription(meta); got != "" {
		t.Errorf("description = %q, want empty — a status banner is not an outcome", got)
	}
}
