package rdd

// REQ-CROSS-013 / TASK-SY-404 — RED-first port of the node op-builder suite
// (mission-control/cli/ops.test.js), plus cross-implementation hash-parity
// pins generated from ops.js itself: the Go builder must produce the SAME
// content hashes so the extractor switch causes zero re-sync churn.

import (
	"strings"
	"testing"
)

func detailWithCriteria() string {
	return strings.Join([]string{
		"- **Status:** READY",
		"- **Acceptance criteria:**",
		"  - GIVEN a thing WHEN poked THEN it reacts.",
		"  - GIVEN only given THEN result.",
		"  - plain statement criterion",
		"- **Tests:** —",
	}, "\n")
}

func TestParseCriteriaSplitsGWTAndStatements(t *testing.T) {
	criteria := ParseCriteria(detailWithCriteria(), "REQ-TST-001")
	if len(criteria) != 3 {
		t.Fatalf("want 3 criteria, got %d", len(criteria))
	}
	first := criteria[0].(map[string]any)
	if first["given"] != "a thing" || first["when"] != "poked" || first["then"] != "it reacts." {
		t.Fatalf("GWT parse wrong: %v", first)
	}
	if first["external_id"] != "REQ-TST-001#AC1" || first["position"] != 1 {
		t.Fatalf("criterion identity wrong: %v", first)
	}
	second := criteria[1].(map[string]any)
	if second["given"] != "only given" || second["then"] != "result." {
		t.Fatalf("GIVEN/THEN (no WHEN) parse wrong: %v", second)
	}
	if _, hasWhen := second["when"]; hasWhen {
		t.Fatalf("no-WHEN criterion must omit the when key: %v", second)
	}
	third := criteria[2].(map[string]any)
	if third["statement"] != "plain statement criterion" {
		t.Fatalf("statement parse wrong: %v", third)
	}
}

// Hash-parity pins — generated by running mission-control/cli/ops.js on the
// same inputs (node, 2026-07-28). If these fail the canonicalization drifted
// from JSON.stringify semantics and the extractor switch would churn hashes.
func TestRequirementOpHashParityWithNodeBuilder(t *testing.T) {
	op := BuildRequirementOp(Req{
		ID:     "REQ-TST-001",
		Title:  `Title with · dots & "quotes"`,
		Ctx:    "TST",
		Stage:  "MVP",
		Status: "READY",
		Source: "`docs/10` · USER:2026-07-22 · EPIC-TST-001 · INV-TST-001",
		Detail: detailWithCriteria(),
	})
	if op.Type != "upsert_requirement" {
		t.Fatalf("wrong type %q", op.Type)
	}
	p := op.Payload
	if p["work_status"] != "READY" || p["context"] != "TST" || p["stage"] != "MVP" {
		t.Fatalf("field mapping wrong: %v", p)
	}
	cites := p["source_citations"].([]any)
	if len(cites) != 4 {
		t.Fatalf("want 4 citations, got %d", len(cites))
	}
	c0 := cites[0].(map[string]any)
	if c0["kind"] != "doc" || c0["ref"] != "docs/10" {
		t.Fatalf("citation classify wrong: %v", c0)
	}
	if c1 := cites[1].(map[string]any); c1["kind"] != "user" {
		t.Fatalf("USER: citation wrong: %v", c1)
	}
	// pins regenerated from the node builder after D-MC-6 added `description`
	const nodeHash = "5782a6941de95140faff1184d435f739c99d11f4fbdc3ed20c758f8d3a655d25"
	if p["content_hash"] != nodeHash {
		t.Fatalf("hash parity broken:\n  go:   %v\n  node: %s", p["content_hash"], nodeHash)
	}
}

func TestEmptyStageHashesAsNullLikeNode(t *testing.T) {
	op := BuildRequirementOp(Req{ID: "REQ-TST-002", Title: "t", Ctx: "TST", Stage: "", Status: "DONE", Source: "—"})
	const nodeHash = "3255be9be181cf85f62f62a3188d34e5b9ab9e8d090f3c195096ea66c06b0c87"
	if op.Payload["content_hash"] != nodeHash {
		t.Fatalf("empty-stage hash parity broken: %v != %s", op.Payload["content_hash"], nodeHash)
	}
	if op.Payload["stage"] != nil {
		t.Fatalf("empty stage must serialize null, got %v", op.Payload["stage"])
	}
}

func TestContentHashKeyOrderIndependent(t *testing.T) {
	a := map[string]any{"x": 1, "y": []any{map[string]any{"b": "2", "a": "1"}}}
	b := map[string]any{"y": []any{map[string]any{"a": "1", "b": "2"}}, "x": 1}
	if ContentHash(a) != ContentHash(b) {
		t.Fatal("hash must be key-order independent")
	}
}

const epicRecord = `# EPIC-TST-001 — Test epic title

Intro.

## Requirements in this epic
` + "`REQ-TST-001` · `REQ-TST-002` · `REQ-TST-001`" + `

## Approval
_pending_
`

func TestEpicOpTitleAndLinksFromRecord(t *testing.T) {
	op := BuildEpicOp(Epic{ID: "EPIC-TST-001"}, epicRecord)
	p := op.Payload
	if p["title"] != "Test epic title" {
		t.Fatalf("title from H1 wrong: %v", p["title"])
	}
	ids := p["requirement_external_ids"].([]any)
	if len(ids) != 2 || ids[0] != "REQ-TST-001" || ids[1] != "REQ-TST-002" {
		t.Fatalf("requirement links wrong: %v", ids)
	}
	if _, has := p["approval"]; has {
		t.Fatal("_pending approval must not sync")
	}
}

func TestEpicOpRecordedApprovalSyncs(t *testing.T) {
	approved := strings.Replace(epicRecord, "_pending_",
		"**APPROVED** — USER:2026-07-22: ship it.", 1)
	op := BuildEpicOp(Epic{ID: "EPIC-TST-001"}, approved)
	approval, ok := op.Payload["approval"].(map[string]any)
	if !ok {
		t.Fatal("recorded approval must sync")
	}
	if approval["source_tag"] != "USER:2026-07-22" || approval["approved_at"] != "2026-07-22T00:00:00.000000Z" {
		t.Fatalf("approval fields wrong: %v", approval)
	}
}

func TestRQGateStates(t *testing.T) {
	answered := BuildRQGateOp(RQ{
		ID: "RQ-101", Title: "T", Heading: "RQ-101 (2026-07-20) T — ✅ APPROVED", Date: "2026-07-20",
		State: "closed", Line: 10, Body: "Resolved per USER:2026-07-20 decision.",
	})
	if answered.Payload["state"] != "answered" || answered.Payload["source_tag"] != "USER:2026-07-20" {
		t.Fatalf("closed RQ with USER tag must answer: %v", answered.Payload)
	}
	if answered.Payload["answerer"].(map[string]any)["kind"] != "human" {
		t.Fatal("answered gate needs a human answerer")
	}

	open := BuildRQGateOp(RQ{ID: "RQ-102", Title: "T2", Heading: "RQ-102 T2 — DECISION NEEDED", State: "decision-needed", Line: 20, Body: "?"})
	if open.Payload["state"] != "open" {
		t.Fatalf("decision-needed RQ must stay open: %v", open.Payload["state"])
	}

	dismissed := BuildRQGateOp(RQ{ID: "RQ-103", Title: "T3", Heading: "RQ-103 T3 ✅", State: "closed", Line: 30, Body: "closed without a source"})
	if dismissed.Payload["state"] != "dismissed" {
		t.Fatalf("closed-without-source must dismiss, never fake an answer: %v", dismissed.Payload["state"])
	}

	oq := BuildOQGateOp(OQ{ID: "OQ-A1", Title: "Where?", Full: "Where does the schema live?", Resolved: true, Line: 5})
	if oq.Payload["state"] != "answered" || oq.Payload["source_tag"] != "DOC:process/08-open-questions.md" {
		t.Fatalf("resolved OQ gets the DOC: tag: %v", oq.Payload)
	}
}

func TestApprovalGateOpenAndClosedForms(t *testing.T) {
	openGate, ok := BuildApprovalGateOp(Epic{ID: "EPIC-TST-001", State: "awaiting-approval", Record: "epics/EPIC-TST-001.md"}, epicRecord)
	if !ok {
		t.Fatal("awaiting-approval epic must gate")
	}
	if openGate.Payload["external_id"] != "APPROVE-EPIC-TST-001" || openGate.Payload["state"] != "open" {
		t.Fatalf("open approval gate wrong: %v", openGate.Payload)
	}
	holds := openGate.Payload["holds"].([]any)
	if len(holds) != 2 {
		t.Fatalf("holds must cover the epic's requirements: %v", holds)
	}

	approved := strings.Replace(epicRecord, "_pending_", "**APPROVED** — USER:2026-07-23: reviewed.", 1)
	closedGate, ok := BuildApprovalGateOp(Epic{ID: "EPIC-TST-001", State: "done"}, approved)
	if !ok {
		t.Fatal("recorded approval must produce the closing gate op")
	}
	if closedGate.Payload["state"] != "answered" || closedGate.Payload["chosen_option_keys"].([]any)[0] != "approve" {
		t.Fatalf("closed approval gate wrong: %v", closedGate.Payload)
	}

	if _, ok := BuildApprovalGateOp(Epic{ID: "EPIC-TST-002", State: "in-progress"}, "no approval here"); ok {
		t.Fatal("an epic neither awaiting nor approved gets no gate")
	}
}

func TestCommitBurstFoldsClosedDaysOnly(t *testing.T) {
	commits := []Commit{
		{Hash: "c3", Date: "2026-07-28T10:00:00+03:00", Subject: "today stays out", IDs: nil},
		{Hash: "c2", Date: "2026-07-27T18:00:00+03:00", Subject: "REQ-TST-001: fix", IDs: []string{"REQ-TST-001"}},
		{Hash: "c1", Date: "2026-07-27T09:00:00+03:00", Subject: "REQ-TST-002: more", IDs: []string{"REQ-TST-002"}},
		{Hash: "c0", Date: "2026-07-26T09:00:00+03:00", Subject: "old", IDs: nil},
	}
	op, ok := BuildCommitBurstOp(commits, "2026-07-28")
	if !ok {
		t.Fatal("closed days exist — burst op expected")
	}
	events := op.Payload["events"].([]any)
	if len(events) != 2 {
		t.Fatalf("want 2 closed days, got %d", len(events))
	}
	newest := events[0].(map[string]any)
	if newest["dedupe_key"] != "commit_burst:2026-07-27" {
		t.Fatalf("days must sort newest first: %v", newest["dedupe_key"])
	}
	payload := newest["payload"].(map[string]any)
	if payload["count"] != 2 || payload["head"] != "c2" {
		t.Fatalf("burst payload wrong: %v", payload)
	}
	if len(newest["related"].([]any)) != 2 {
		t.Fatalf("related ids wrong: %v", newest["related"])
	}
	if op.Payload["external_id"] != "EVENTS-COMMITS-2026-07-28" {
		t.Fatalf("burst external id wrong: %v", op.Payload["external_id"])
	}
}

func TestExtractTracePaths(t *testing.T) {
	detail := strings.Join([]string{
		"- **Tests:** `apps/x/test/a_test.exs` (5) · `go test ./cmd`",
		"- **Code:** `tools/modernpath/cmd/factory.go` · `mix esbuild` · plain words",
	}, "\n")
	paths := ExtractTracePaths(detail)
	want := []string{"apps/x/test/a_test.exs", "tools/modernpath/cmd/factory.go"}
	if len(paths) != len(want) || paths[0] != want[0] || paths[1] != want[1] {
		t.Fatalf("trace paths wrong: %v", paths)
	}
}

func TestBuildOpsOrderAndObsoleteFilter(t *testing.T) {
	data := Data{
		Reqs: []Req{
			{ID: "REQ-TST-001", Status: "READY", Ctx: "TST"},
			{ID: "REQ-TST-009", Status: "OBSOLETE", Ctx: "TST"},
		},
		Epics: []Epic{{ID: "EPIC-TST-001", State: "in-progress"}},
		RQs: []RQ{
			{ID: "RQ-1", State: "finding", Line: 1},
			{ID: "RQ-2", State: "decision-needed", Line: 2},
		},
		OQs: []OQ{{ID: "OQ-1", Full: "q", Line: 3}},
	}
	ops := BuildOps(data, nil, "2026-07-28")
	if len(ops) != 4 {
		t.Fatalf("want 4 ops (1 req, 1 epic, 2 gates), got %d", len(ops))
	}
	if ops[0].Type != "upsert_requirement" || ops[1].Type != "upsert_epic" || ops[2].Type != "upsert_gate" {
		t.Fatalf("dependency order wrong: %v %v %v", ops[0].Type, ops[1].Type, ops[2].Type)
	}
	for _, op := range ops {
		if op.Payload["external_id"] == "REQ-TST-009" {
			t.Fatal("OBSOLETE rows must not sync")
		}
		if op.Payload["external_id"] == "RQ-1" {
			t.Fatal("finding RQs must not become gates")
		}
	}
}

// ---------------------------------------------------------------- epic specs (REQ-CROSS-023/024, EPIC-SYNC-006)

const speccedRecord = `# EPIC-TST-005 — Specced epic

## Specification status
SPEC-READY — awaiting the gate.

## Requirements in this epic
` + "`REQ-TST-009`" + `

## Approval
_pending_
`

func specFixtures() []EpicSpec {
	return []EpicSpec{
		{Rel: "epics/EPIC-TST-005-x/specs/architecture.md", Name: "architecture.md", Content: "# Arch"},
		{Rel: "epics/EPIC-TST-005-x/specs/requirements.md", Name: "requirements.md", Content: "# Reqs"},
	}
}

func folderEpic(state string) Epic {
	return Epic{ID: "EPIC-TST-005", State: state, Record: "epics/EPIC-TST-005-x/EPIC.md", Specs: specFixtures()}
}

func TestEpicOpSpecsPresenceRule(t *testing.T) {
	// folder-form epic: specs present, ordered, positioned
	op := BuildEpicOp(folderEpic("proposed"), speccedRecord)
	specs, ok := op.Payload["specs"].([]any)
	if !ok || len(specs) != 2 {
		t.Fatalf("folder epic must carry its specs: %v", op.Payload["specs"])
	}
	first := specs[0].(map[string]any)
	if first["external_id"] != "epics/EPIC-TST-005-x/specs/architecture.md" ||
		first["name"] != "architecture.md" || first["position"] != 1 || first["content_md"] != "# Arch" {
		t.Fatalf("spec item shape wrong: %v", first)
	}

	// folder-form with no specs: present-empty (archives server-side)
	empty := BuildEpicOp(Epic{ID: "EPIC-TST-006", Record: "epics/EPIC-TST-006-y/EPIC.md"}, "# EPIC-TST-006 — Empty")
	if v, has := empty.Payload["specs"]; !has {
		t.Fatal("folder epic without specs must carry present-empty specs")
	} else if len(v.([]any)) != 0 {
		t.Fatalf("expected empty specs, got %v", v)
	}

	// file-form epic: key absent (never touches server artifacts)
	file := BuildEpicOp(Epic{ID: "EPIC-TST-001", Record: "epics/EPIC-TST-001.md"}, epicRecord)
	if _, has := file.Payload["specs"]; has {
		t.Fatal("file-form epic must not carry a specs key")
	}
}

func TestEpicOpSpecContentCapped(t *testing.T) {
	big := strings.Repeat("a", 70000)
	epic := Epic{ID: "EPIC-TST-007", Record: "epics/EPIC-TST-007-z/EPIC.md",
		Specs: []EpicSpec{{Rel: "epics/EPIC-TST-007-z/specs/requirements.md", Name: "requirements.md", Content: big}}}
	op := BuildEpicOp(epic, "# EPIC-TST-007 — Big")
	content := op.Payload["specs"].([]any)[0].(map[string]any)["content_md"].(string)
	if len(content) != 65536 {
		t.Fatalf("spec content must cap at 65536, got %d", len(content))
	}
}

func TestSpecApprovalLineClassification(t *testing.T) {
	cases := []struct {
		text, want string
	}{
		{speccedRecord, "ready"},
		{strings.Replace(speccedRecord, "SPEC-READY — awaiting the gate.", "SPEC-DRAFT — writing.", 1), "draft"},
		{strings.Replace(speccedRecord, "SPEC-READY — awaiting the gate.", "SPEC-APPROVED — reviewed · USER:2026-08-05", 1), "approved"},
		// APPROVED without a USER tag is NOT an approval (honesty rule)
		{strings.Replace(speccedRecord, "SPEC-READY — awaiting the gate.", "SPEC-APPROVED — someone said ok", 1), "ready"},
		{epicRecord, ""},        // no section = legacy
		{"## Specification status\nThe specs live in specs/ and are prose.\n", ""}, // section, no marker = legacy
	}
	for i, c := range cases {
		if got, _ := SpecApprovalLineOf(c.text); got != c.want {
			t.Fatalf("case %d: want %q, got %q", i, c.want, got)
		}
	}
}

func TestSpecApprovalGateOpenAnsweredAndLegacyForms(t *testing.T) {
	// SPEC-READY + specs → open gate holding the epic
	openGate, ok := BuildSpecApprovalGateOp(folderEpic("proposed"), speccedRecord)
	if !ok {
		t.Fatal("SPEC-READY folder epic with specs must gate")
	}
	p := openGate.Payload
	if p["external_id"] != "SPEC-APPROVE-EPIC-TST-005" || p["kind"] != "spec_approval" || p["state"] != "open" {
		t.Fatalf("open spec gate wrong: %v", p)
	}
	holds := p["holds"].([]any)
	if len(holds) != 1 || holds[0].(map[string]any)["held_external_id"] != "EPIC-TST-005" ||
		holds[0].(map[string]any)["held_entity_type"] != "epic" {
		t.Fatalf("spec gate must hold the epic: %v", holds)
	}
	if body := p["body_md"].(string); !strings.Contains(body, "architecture.md") {
		t.Fatalf("body must index the specs: %q", body)
	}

	// SPEC-APPROVED … USER: → answered form
	approved := strings.Replace(speccedRecord, "SPEC-READY — awaiting the gate.",
		"SPEC-APPROVED — reviewed and accepted · USER:2026-08-05 (SPEC-APPROVE-EPIC-TST-005)", 1)
	closedGate, ok := BuildSpecApprovalGateOp(folderEpic("in-progress"), approved)
	if !ok {
		t.Fatal("SPEC-APPROVED must produce the answered gate op")
	}
	if closedGate.Payload["state"] != "answered" || closedGate.Payload["source_tag"] != "USER:2026-08-05" ||
		closedGate.Payload["chosen_option_keys"].([]any)[0] != "approve" {
		t.Fatalf("answered spec gate wrong: %v", closedGate.Payload)
	}

	// SPEC-DRAFT: no gate
	draft := strings.Replace(speccedRecord, "SPEC-READY — awaiting the gate.", "SPEC-DRAFT — writing.", 1)
	if _, ok := BuildSpecApprovalGateOp(folderEpic("proposed"), draft); ok {
		t.Fatal("SPEC-DRAFT must not gate")
	}

	// legacy (no marker) and file-form epics: no gate
	if _, ok := BuildSpecApprovalGateOp(Epic{ID: "EPIC-TST-001", Record: "epics/EPIC-TST-001.md"}, epicRecord); ok {
		t.Fatal("legacy epic must not gate")
	}

	// SPEC-READY but no specs: no gate (an approval over nothing is dishonest)
	noSpecs := Epic{ID: "EPIC-TST-005", Record: "epics/EPIC-TST-005-x/EPIC.md"}
	if _, ok := BuildSpecApprovalGateOp(noSpecs, speccedRecord); ok {
		t.Fatal("SPEC-READY with no specs must not gate")
	}
}

// REQ-PLN-054 / D-MC-6 (USER:2026-08-07): a requirement's one-line description
// comes from its detail block's **Statement:** line; where the ledger has none
// (~69% of rows at decision time) it falls back to the first criterion's THEN
// clause — the outcome half reads as a summary where the full GWT does not.
// Neither present → empty (never invent one).
func TestParseDescriptionPrefersStatementThenFallsBackToThen(t *testing.T) {
	withStatement := "- **Status:** DONE\n- **Statement:** The face shows every model we can call.\n" +
		"- **Acceptance criteria:**\n  - GIVEN a user WHEN it loads THEN the catalog renders.\n"
	if got := ParseDescription(withStatement); got != "The face shows every model we can call." {
		t.Fatalf("statement not used: %q", got)
	}

	criteriaOnly := "- **Status:** DONE\n- **Acceptance criteria:**\n" +
		"  - GIVEN a batch WHEN applied THEN the release row exists and every row carries its id.\n"
	if got := ParseDescription(criteriaOnly); got != "The release row exists and every row carries its id." {
		t.Fatalf("THEN fallback wrong: %q", got)
	}

	if got := ParseDescription("- **Status:** DONE\n- **Tests:** —\n"); got != "" {
		t.Fatalf("expected empty, got %q", got)
	}
	if got := ParseDescription(""); got != "" {
		t.Fatalf("expected empty for no detail, got %q", got)
	}
}

// REQ-PLN-054 / TASK-MC-107: an epic's description is its "## User outcome"
// section — first paragraph, folded to one line. 34 of 139 records have no
// such heading; those carry no description rather than an invented one, so the
// key is absent from the payload (and their content hashes do not move).
func TestParseEpicDescriptionUsesUserOutcomeSection(t *testing.T) {
	record := "# EPIC-MC-001 — Scope face\n\n- **Status:** IN_REVIEW\n\n" +
		"## User outcome (UR-MC-001)\nSomeone opening the scope face sees\nthe entire ledger at once.\n\n" +
		"A second paragraph that is not the summary.\n\n## Decisions\n| ID | Q |\n"
	want := "Someone opening the scope face sees the entire ledger at once."
	if got := ParseEpicDescription(record); got != want {
		t.Fatalf("user outcome not folded to one line:\n  got:  %q\n  want: %q", got, want)
	}

	if got := ParseEpicDescription("# EPIC-X — No outcome\n\n## Tasks\n- TASK-1\n"); got != "" {
		t.Fatalf("expected empty without the heading, got %q", got)
	}

	op := BuildEpicOp(Epic{ID: "EPIC-X", Record: "epics/EPIC-X.md"}, "# EPIC-X — t\n\n## Tasks\n- a\n")
	if _, present := op.Payload["description"]; present {
		t.Fatal("description key must be absent when there is no user outcome")
	}
}

// REQ-CROSS-028 / SCN-SY-060+061: an epic's loop state is recorded in
// WORKLIST's own "Upper status" / "Lower status" columns (127 of 146 rows carry
// both) and was thrown away — only the Overall cell was read, to decide whether
// to open an approval gate. `initiatives.status` is NOT the target: it is the
// board column, which SERVER-SYNC-DESIGN §1.3 marks "untouched" and Core.Sync
// refuses to overwrite ("moving cards is the board's job").
func TestBuildEpicOpCarriesWorklistLoopStatuses(t *testing.T) {
	epic := Epic{
		ID:     "EPIC-X-001",
		Record: "epics/EPIC-X-001.md",
		Upper:  "UPPER_VALIDATED (live browser pass)",
		Lower:  "LOWER_VERIFIED",
	}
	p := BuildEpicOp(epic, "# EPIC-X-001 — t\n").Payload
	if p["upper_loop_status"] != "UPPER_VALIDATED (live browser pass)" {
		t.Fatalf("upper loop status not carried: %v", p["upper_loop_status"])
	}
	if p["lower_loop_status"] != "LOWER_VERIFIED" {
		t.Fatalf("lower loop status not carried: %v", p["lower_loop_status"])
	}
	if _, present := p["status"]; present {
		t.Fatal("must not send a board status — sync never moves cards (SERVER-SYNC-DESIGN §1.3)")
	}

	// An empty or em-dash cell is absence, not a status: the key stays off the
	// payload so those epics' content hashes do not move.
	bare := BuildEpicOp(Epic{ID: "EPIC-X-002", Record: "epics/EPIC-X-002.md", Upper: "—", Lower: ""}, "# EPIC-X-002 — t\n").Payload
	if _, present := bare["upper_loop_status"]; present {
		t.Fatal("em-dash must not sync as a status")
	}
	if _, present := bare["lower_loop_status"]; present {
		t.Fatal("empty cell must not sync as a status")
	}
}

// REQ-CROSS-028 / SCN-SY-062+063: SCN tables become scenario-kind criteria.
// The server has accepted them since M4 (Core.Sync passes payload `scenarios`
// through sync_criteria with owner :initiative_id) — no builder ever sent any.
// Six header shapes exist across the records, so the text column is chosen by
// header name where recognizable and by longest cell otherwise.
func TestParseScenariosAcrossHeaderShapes(t *testing.T) {
	cases := []struct{ name, section, wantID, wantText string }{
		{
			name: "SCN | Summary | Status",
			section: "## BDD acceptance scenarios (SCN — upper loop)\n" +
				"| SCN | Summary | Status |\n|---|---|---|\n" +
				"| SCN-SY-001 | Selecting a system re-queries with the id. | LOWER_VERIFIED |\n",
			wantID: "SCN-SY-001", wantText: "Selecting a system re-queries with the id.",
		},
		{
			name: "Scenario | Requirement | Statement | Status — the id column is not the text column",
			section: "## Acceptance scenarios\n" +
				"| Scenario | Requirement | Statement | Status |\n|---|---|---|---|\n" +
				"| SCN-SY-041 | REQ-CROSS-017 | GIVEN a batch WHEN applied THEN the release exists | DONE |\n",
			wantID: "SCN-SY-041", wantText: "GIVEN a batch WHEN applied THEN the release exists",
		},
		{
			name: "Scenario | Summary | Failing evidence | Passing evidence — evidence cells must not win",
			section: "## BDD acceptance scenarios\n" +
				"| Scenario | Summary | Failing evidence | Passing evidence |\n|---|---|---|---|\n" +
				"| SCN-RK-001 | The risk form offers all ten fields. | RED core 5/5; RED FE 3/3 with a very long trailing evidence note that is longer than the summary | core 5/5; FE 3/3 |\n",
			wantID: "SCN-RK-001", wantText: "The risk form offers all ten fields.",
		},
	}
	for _, c := range cases {
		got := ParseScenarios("# EPIC-T — t\n\n"+c.section+"\n## Next\n", "EPIC-T")
		if len(got) != 1 {
			t.Fatalf("%s: expected 1 scenario, got %d", c.name, len(got))
		}
		s := got[0].(map[string]any)
		// Owner-namespaced, like requirement criteria (REQ-CMP-010#AC1): SCN ids
		// are scoped by AREA, not by epic — 85 prefixes across the records — so
		// two epics in one area legitimately reach for the same SCN id.
		if s["external_id"] != "EPIC-T#"+c.wantID {
			t.Errorf("%s: id = %v, want EPIC-T#%s", c.name, s["external_id"], c.wantID)
		}
		if s["kind"] != "scenario" {
			t.Errorf("%s: kind = %v, want scenario", c.name, s["kind"])
		}
		text, _ := s["statement"].(string)
		if g, ok := s["given"].(string); ok {
			text = "GIVEN " + g + " WHEN " + s["when"].(string) + " THEN " + s["then"].(string)
		}
		if text != c.wantText {
			t.Errorf("%s:\n  got  %q\n  want %q", c.name, text, c.wantText)
		}
	}

	// 26 records carry the heading with no table beneath it: no scenarios, and
	// no `scenarios` key on the payload, so their hashes do not move.
	if got := ParseScenarios("# E — t\n\n## Acceptance scenarios\n_pending_\n", "E"); len(got) != 0 {
		t.Fatalf("headingless-table must yield no scenarios, got %d", len(got))
	}
	if _, present := BuildEpicOp(Epic{ID: "E", Record: "epics/E.md"}, "# E — t\n").Payload["scenarios"]; present {
		t.Fatal("no scenarios must mean no key (hash stability)")
	}
}

// REQ-CROSS-028 follow-up (USER:2026-08-07): two DIFFERENT epics in the same
// area share an SCN id — SCN-AK-001 belongs to both EPIC-FE-034 ("API keys:
// least-privilege scope selection") and EPIC-PORTFOLIO-038 ("API key
// management"). acceptance_criteria.external_id is unique per tenant, so the
// second sync stole the row and 9 epics served zero scenarios. Owner-namespacing
// makes the collision impossible by construction rather than by convention.
func TestScenarioIDsAreNamespacedByTheirEpic(t *testing.T) {
	section := "## Acceptance scenarios\n| SCN | Summary | Status |\n|---|---|---|\n" +
		"| SCN-AK-001 | The key form offers every scope. | DONE |\n"

	a := BuildEpicOp(Epic{ID: "EPIC-FE-034", Record: "epics/EPIC-FE-034.md"}, "# EPIC-FE-034 — t\n\n"+section)
	b := BuildEpicOp(Epic{ID: "EPIC-PORTFOLIO-038", Record: "epics/EPIC-PORTFOLIO-038.md"}, "# EPIC-PORTFOLIO-038 — t\n\n"+section)

	idOf := func(op Op) string {
		return op.Payload["scenarios"].([]any)[0].(map[string]any)["external_id"].(string)
	}
	if idOf(a) == idOf(b) {
		t.Fatalf("two epics must not claim one criterion row: both got %q", idOf(a))
	}
	if idOf(a) != "EPIC-FE-034#SCN-AK-001" {
		t.Errorf("id = %q, want EPIC-FE-034#SCN-AK-001", idOf(a))
	}
	if idOf(b) != "EPIC-PORTFOLIO-038#SCN-AK-001" {
		t.Errorf("id = %q, want EPIC-PORTFOLIO-038#SCN-AK-001", idOf(b))
	}
}

// REQ-CROSS-031: the generic RDD framework puts a context's ledger at
// libs/<ctx>/REQUIREMENTS.md — context in the DIRECTORY — while this workspace
// uses tasks/<CTX>-REQUIREMENTS.md. Only the second was accepted, so the first
// real client repository had all 19 of its ledgers skipped and synced 0 ops.
// Both layouts are the documented convention; both must parse.
func TestParseLedgerAcceptsDirectoryScopedContext(t *testing.T) {
	body := "## Dashboard — BNK\nTotals: 1 DONE\n\n" +
		"| ID | Title | Stage | Status | Source | Tests | Code |\n|--|--|--|--|--|--|--|\n" +
		"| REQ-BNK-001 | Statement ingestion | P | DONE | x | t | c |\n"

	for _, path := range []string{
		"tasks/BNK-REQUIREMENTS.md",  // this workspace
		"libs/bnk/REQUIREMENTS.md",   // the generic framework
		"libs/BNK/REQUIREMENTS.md",   // either case
	} {
		reqs := ParseLedger(path, body)
		if len(reqs) != 1 {
			t.Fatalf("%s: expected 1 requirement, got %d", path, len(reqs))
		}
		if reqs[0].Ctx != "BNK" {
			t.Errorf("%s: context = %q, want BNK", path, reqs[0].Ctx)
		}
		if reqs[0].ID != "REQ-BNK-001" {
			t.Errorf("%s: id = %q", path, reqs[0].ID)
		}
	}

	// A bare REQUIREMENTS.md with no context directory is still skipped — there
	// is nothing to derive a context from, and guessing would mislabel rows.
	if reqs := ParseLedger("REQUIREMENTS.md", body); reqs != nil {
		t.Errorf("a context-less REQUIREMENTS.md must be skipped, got %d", len(reqs))
	}
}

// REQ-CROSS-031: a markdown table cell may contain an escaped pipe. Splitting
// naively on "|" shifts every column after it, so a requirement whose TITLE
// contains \|difference\| had prose parsed as its work_status and the server
// rejected the whole batch at op 285 — after 284 had already applied.
func TestSplitCellsRespectsEscapedPipes(t *testing.T) {
	line := `| REQ-AP-103 | Reduces \|difference\| toward zero | A4 | DONE | src | t | c |`
	cells := splitCells(line)
	if len(cells) < 5 {
		t.Fatalf("too few cells: %d (%q)", len(cells), cells)
	}
	if cells[1] != "REQ-AP-103" {
		t.Errorf("id cell = %q", cells[1])
	}
	if cells[2] != "Reduces |difference| toward zero" {
		t.Errorf("title cell = %q — the escape should be resolved, not split on", cells[2])
	}
	if cells[4] != "DONE" {
		t.Errorf("status cell = %q, want DONE — columns shifted", cells[4])
	}
}

// REQ-CROSS-031: a ledger's status cell carries the vocabulary term, sometimes
// with a human qualifier or markdown emphasis around it — "DONE (DEMO-GRADE)",
// "**DONE**". The term is what the contract validates; the qualifier is prose
// that belongs to the ledger. Sending the whole cell got the batch rejected at
// op 1363 with 1362 already applied.
func TestParseLedgerNormalisesQualifiedStatuses(t *testing.T) {
	rows := map[string]string{
		"DONE (DEMO-GRADE)":            "DONE",
		"**DONE**":                     "DONE",
		"DEFERRED — waiting on GAP-009": "DEFERRED",
		"IN_REVIEW":                    "IN_REVIEW",
	}
	for cell, want := range rows {
		body := "## Dashboard — TAX\nTotals: 1 DONE\n\n| ID | Title | Stage | Status |\n|--|--|--|--|\n" +
			"| REQ-TAX-001 | a thing | F1 | " + cell + " |\n"
		reqs := ParseLedger("libs/tax/REQUIREMENTS.md", body)
		if len(reqs) != 1 {
			t.Fatalf("%q: expected 1 requirement, got %d", cell, len(reqs))
		}
		if reqs[0].Status != want {
			t.Errorf("%q → status %q, want %q", cell, reqs[0].Status, want)
		}
	}
}
